### ISSUE TITLE
import function implementation question

### ISSUE THREAD

**Issue by aaltonenzhang** [WAVM/WAVM#103]
In Source/Emscripten.cpp, there is an implementation for ___syscall146, "DEFINE_INTRINSIC_FUNCTION_WITH_MEM_AND_TABLE(env,"___syscall146",I32,___syscall146,I32 file,I32 argsPtr)".
I have asked emsdk writer about the argument here, it seems that for all syscall functions, the first argument should be the syscall number, and the second argument is the argument pointer. So I think the “I32 file” here is not correct, the file should be moved in to the args[0]. Is that right?

**Comment by AndrewScheidecker** [comment]
In this case, the syscall number is implied by the function that is called: `__syscall146(...)` corresponds to `syscall(146, ...)`.

This code is trying to emulate the internal API provided by the JavaScript code Emscripten bundles with your WebAssembly code, so it's vulnerable to changes that Emscripten makes to that internal API.

This code works for code compiled with some version Emscripten (see [Test/zlib/zlib.wast](https://github.com/AndrewScheidecker/WAVM/blob/master/Test/zlib/zlib.wast), which was compiled by Emscripten and calls `__syscall146`). However, it's possible it doesn't work with code compiled by newer versions of Emscripten.

Are you having a problem running code that calls `__syscall146`?

**Comment by AndrewScheidecker** [comment]
Please feel free to reopen this issue if you have further questions.
