### ISSUE TITLE
enable libfuzzer will failed to compile the program

### ISSUE THREAD

**Issue by maldiohead** [WAVM/WAVM#112]
![default](https://user-images.githubusercontent.com/23315692/45605382-3cdc3200-ba6f-11e8-96a1-ba7ca820d2b6.png)

**Comment by AndrewScheidecker** [comment]
Are you enabling it by setting `CXXFLAGS`? If so, you should instead enable WAVM's `ENABLE_LIBFUZZER` CMake option. That will set the appropriate compile flags, and also disable the `main` functions defined in the fuzzing targets.

**Comment by maldiohead** [comment]
after I make the Main function as comments. compiled successfully
