### ISSUE TITLE
Standard compliance question

### ISSUE THREAD

**Issue by kyr0** [WAVM/WAVM#113]
Hi,

I'm impressed by this project. Very nice implementation and clean code. I was wondering about it's standard compliance. Is the project already 100% WebAssembly design spec compliant?

I'm asking because I'm thinking about adding scripting to an application I'm writing in C++.
The whole point is, that I would like to have a near-native performance for some DSP calculations and a simple to use scripting language.

AssemblyScript is the scripting language I'm using (TypeScript based, basically typed JavaScript)... it compiles my DSP code to WASM module code. Now, if I imagine the users of the program could simple script in AssemblyScript, hit "run" and I would spawn a WAVM process..., this would be quite nice :)

But it depends on if WAVM is already standards compliant :)

Thanks and best,
Aron

**Comment by AndrewScheidecker** [comment]
WAVM passes all of the tests in the WebAssembly MVP (i.e. version 1) spec repo. That's not a definitive test of compliance, but I would guess that for anything in the standard that's not covered by the test suite, that it's just as likely to be broken in browsers as it is in WAVM.

The various WebAssembly extensions that WAVM implements are further from standardization, still changing, and have less test coverage. It's more likely that WAVM implements some of those extensions incorrectly, but I believe WAVM's implementations of the mutable globals, extended names section, simd, threads, non-trapping float-to-int, sign-extension, multi-value, bulk-memory-operations, and reference-types extensions to be complete. The exception-handling extension is still undergoing dramatic changes, so WAVM's implementation is behind what is currently proposed.

I am aware of one issue where WAVM doesn't match the proposed SIMD extension: https://github.com/WAVM/WAVM/issues/66. It's not too hard to fix, but has been low priority.
