### ISSUE TITLE
Links in the README.md now largely broken

### ISSUE THREAD

**Issue by justinclift** [WAVM/WAVM#117]
Just went to create a PR with updated links in the README.md... however although some are obvious (eg IR → Include/WAVM/IR) it's pretty hard to tell what the remaining urls should really be eg "Runtime" section.

Suspecting that area will need a rewrite, not just link correction.

Someone already familiar with the project could likely get this done in less than 10 mins, and help future people grok the project easier. :smile:

**Comment by AndrewScheidecker** [comment]
Thanks for pointing that out. I fixed the links, and updated the exposition a little bit in https://github.com/WAVM/WAVM/commit/b8583cbd0c73ef3f026ce98110496708eb2a7a07 and https://github.com/WAVM/WAVM/commit/3f7e2f7cb3543e79c440e08ff4ecc752cee6ce76.

**Comment by justinclift** [comment]
Thanks heaps @AndrewScheidecker, looks good. :smile:
