### ISSUE TITLE
Unable to run clang build .wast code

### ISSUE THREAD

**Issue by syzh** [WAVM/WAVM#119]
[root@localhost ~]# clang -emit-llvm -O3 --std=c++14 --target=wasm32 -ffreestanding -o webasm.bc -c webasm.cpp
[root@localhost ~]# clang -emit-llvm -O3 --std=c++14 --target=wasm32 -o webasm.bc -c webasm.cpp
[root@localhost ~]# llc -thread-model=single -asm-verbose=false -o webasm.s webasm.bc
[root@localhost ~]# s2wasm -o webasm.wast -s 10240 webasm.s
[root@localhost ~]# wavm-run webasm.wast
Generated stub for missing import env.printf : func (i32, i32)->i32
Module does not declare a default memory object to put arguments in.

[root@localhost ~]# wast2wasm webasm.wast webasm.wasm -n
[root@localhost ~]# wavm-run webasm.wasm
Generated stub for missing import env.printf : func (i32, i32)->i32
Module does not declare a default memory object to put arguments in

this webasm.cpp code:

#include <stdio.h>

int main(int argc, char *argv[]) {
  int a = 10;
  printf("hello asm %d\n", a);
  return 0;
}

clang/llc tool version:
[root@localhost ~]# clang -v
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64

[root@localhost ~]# llc -version
LLVM (http://llvm.org/):
  LLVM version 6.0.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake

  Registered Targets:
    wasm32 - WebAssembly 32-bit
    wasm64 - WebAssembly 64-bit
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
help me!

**Comment by AndrewScheidecker** [comment]
The problem here is that you need to link with a libc implementation that provides `printf`. I'm not sure how to do that with s2wasm. Emscripten does all this for you, so that's currently the easiest way to do it, but if you don't want to use it, there are a few other toolchains (compiler+linker+libraries) that you can use. One that I'm developing alongside a WAVM-based runtime is [Wavix](https://github.com/WAVM/Wavix).
