### ISSUE TITLE
Repeat invocations

### ISSUE THREAD

**Issue by Shillaker** [WAVM/WAVM#122]
Hi Andrew. I have a scenario where I'd like to repeatedly execute a given wasm function in a loop, reusing the same `Function`, `ModuleInstance`, `Compartment` and `Context` objects if possible. For a simple no-op I'd imagine repeat calls to `invokeFunctionChecked` with the same `Function` object would be ok, but anything that manipulates memory could leave an impression that impacts subsequent invocations (unless I introduce some kind of clean-up). 

My question is, what are the minimal steps after a function invocation to "reset" it and give the next invocation of that same function a clean slate? Is it possible to create a new memory array and swap it out for the old one? Would I need a new compartment/ context each time? I could of course move the whole `instantiateModule` cycle inside the loop to guarantee a fresh copy every time, but ideally I'd like to keep this loop as efficient as possible.

Thanks

**Comment by Shillaker** [comment]
I think I've answered my own question. From what I can see, I can reuse everything provided:

- Before the first invocation I take a "clean" copy of the default memory and record its number of pages
- For each invocation I create a new `Context`
- After the invocation has finished, I grow/ shrink the module's memory back to the original number of pages, then copy the "clean" contents back into place

So far this hasn't broken... Does that sound sensible?

**Comment by AndrewScheidecker** [comment]
That seems reasonable. I would only add that you could let WAVM do some of that work by using the `cloneCompartment`/`cloneContext` APIs that are used by Wavix's fork syscall.

**Comment by Xavier1994** [comment]
hi, @Shillaker I' m doing the same thing here, can i have your sample code?

**Comment by Shillaker** [comment]
Hi @Xavier1994 , I don't have any sample code as such, but you can see where we reset WAVM modules in Faasm in the `clone` method here: https://github.com/faasm/faasm/blob/master/src/wavm/WAVMWasmModule.cpp#L118 . There is a lot more code than you'd need for a simple use-case, but essentially it's a case of using `cloneCompartment` and `cloneContext` to restore clean versions respectively.

Simpler examples can be found in the WAVM tests, e.g. grep this file for `clone`: https://github.com/WAVM/WAVM/blob/master/Programs/wavm/Testing/RunTestScript.cpp.

**Comment by Xavier1994** [comment]
@Shillaker thank you for your answer, I use cloneCompartment and cloneContext, but it is still too slow to call clone cloneCompartment/cloneContext/remapToClonedCompartment. my situation is using wasm as a udf function in an OLTP database, So i want the function call as lightweight as possible. Is there any better way？

**Comment by Shillaker** [comment]
The approach described above will guarantee you a clean copy, but there may be certain short-cuts depending on your use-case. You'll have to be more precise though, what do you mean by "too slow"? Which of the three calls you mention is contributing the most overhead and which part of that call is taking the time? Have you profiled it at all? 

You may find that copying the whole linear memory each time is unnecessary, so you can perform some shortcuts there, but it's only worth it if you know that that's the bottleneck in your system. This is getting into fairly niche requirements and is not something I personally would expect a project like WAVM to support, so you need to be ready to get your hands dirty and make some changes yourself.

**Comment by Shillaker** [comment]
... if you do find that copying linear memory is the thing that takes time, you may consider adopting the approach taken in Faasm which uses a type of snapshot and restore. First off we modified `cloneCompartment` to avoid performing the memory copy (in [our case](https://github.com/faasm/WAVM/blob/faasm/Lib/Runtime/Compartment.cpp#L68) we added a flag but you may just remove it completely).

Your UDF execution might then look something like:

- Take a snapshot of the linear memory before executing the UDF (this could be done once for the whole system or once per user depending on your requirements)
- Execute the UDF
- Perform the reset process we've already discussed but using your new version of `cloneCompartment` (i.e. not copying the memory)
- Reset the memory yourself, how you do this will depend on your requirements.

In Faasm we restore the memory using copy-on-write memory, hence the restore time is quick and we avoid any unnecessary overhead from duplicating lots of linear memories. This process is kicked off [here](https://github.com/faasm/faasm/blob/master/src/wasm/WasmModule.cpp#L121).

If you're interested in near-data processing and offloading with WebAssembly you can have a look at [Shredder](https://dl.acm.org/doi/abs/10.1145/3357223.3362723) which uses V8. They focus on Javascript but as they mention in the paper, their approach could also be used with WebAssembly.

**Comment by Xavier1994** [comment]
![image](https://user-images.githubusercontent.com/11145343/117532287-4304ef80-b019-11eb-9d46-7b4bc1c4f7a8.png)

yes, almost spending on copying linear memory,  thank you for advice

**Comment by Xavier1994** [comment]
hi, @Shillaker can i ask a more question?  my UDF function's input is a complicated struct, I can encode it to a binary, But how can i pass it into wasm code,  now I use memset to copy the binary into instance's Memory header, so i can use the offset to get the binary and decode it  in the wasm code.   but i'm not sure it is the correct way, because i can't guarantee whether the memory can be modified

**Comment by Shillaker** [comment]
Copying the struct into the linear memory is definitely the right approach, although I would do two things:

- Allocate some _new_ memory and copy the struct into that
- Pass the offset of this new region to the the function

To allocate the new memory you can use [`Runtime::growMemory`](https://github.com/WAVM/WAVM/blob/master/Include/WAVM/Runtime/Runtime.h#L373), and the `outOldNumPages` parameter will tell you the offset of the new memory region. Then you can use [`Runtime::memoryRef`](https://github.com/WAVM/WAVM/blob/master/Include/WAVM/Runtime/Runtime.h#L388) to get a native pointer, and `memcpy` the struct into that.

If the function is already expecting a pointer to its input, you would pass the offset to the new memory region using that, otherwise you could modify the `argc`/ `argv`, or you could write a custom intrinsic funciton like `getInput()` which the code would call to get its input (then this function could return the pointer).
