### ISSUE TITLE
Use WAVM as a library

### ISSUE THREAD

**Issue by quangIO** [WAVM/WAVM#128]
I want to embed WAVM in my C++ application. My cmake file is something like this, 
```cmake
find_package(LLVM REQUIRED CONFIG)

include_directories(${LLVM_INCLUDE_DIRS})
add_definitions(${LLVM_DEFINITIONS})

include_directories(
        ${WAVM_HOME}/Include
        ${WAVM_HOME}/wasm_build/Include
)

target_link_libraries(testwasm PUBLIC
        ${WAVM_HOME}/wasm_build/Lib/Runtime/libRuntime.so
        ${WAVM_HOME}/wasm_build/Lib/WASM/libWASM.so)
```

But when I build, there are errors like `unknown type name 'PLATFORM_API'`. Is there any tutorial about how to use WAVM as a library? Thanks.

Edit: If anyone has the same problem, I am managed to build it with 
```cmake
...
set(CMAKE_CXX_COMPILER "clang++")
target_link_libraries(testwasm PUBLIC
        ....
        ${WAVM_HOME}/wasm_build/Lib/IR/libIR.a
        ${WAVM_HOME}/wasm_build/Lib/Emscripten/libEmscripten.a
        ${WAVM_HOME}/wasm_build/Lib/RegExp/libRegExp.a
        ${WAVM_HOME}/wasm_build/Lib/Logging/libLogging.a
        ${WAVM_HOME}/wasm_build/Lib/ThreadTest/libThreadTest.a
        ${WAVM_HOME}/wasm_build/Lib/LLVMJIT/libLLVMJIT.a
        ${WAVM_HOME}/wasm_build/Lib/NFA/libNFA.a
        ${WAVM_HOME}/wasm_build/Lib/WASTPrint/libWASTPrint.a
        ${WAVM_HOME}/wasm_build/Lib/WASTParse/libWASTParse.a
        ${WAVM_HOME}/wasm_build/Lib/WASM/libWASM.a
        ${WAVM_HOME}/wasm_build/Lib/Runtime/libRuntime.a
        ${WAVM_HOME}/wasm_build/Lib/Platform/libPlatform.a)
```

and include these macros:
```c++
#define IR_API __attribute__((visibility("default")))
#define PLATFORM_API __attribute__((visibility("default")))
#define RUNTIME_API __attribute__((visibility("default")))
#define EMSCRIPTEN_API __attribute__((visibility("default")))
#define LOGGING_API __attribute__((visibility("default")))
#define THREADTEST_API __attribute__((visibility("default")))
#define WASM_API __attribute__((visibility("default")))
#define WASTPARSE_API __attribute__((visibility("default")))
```

Quite ugly tho.

**Comment by quangIO** [comment]
Thanks, by the way, I think there are some bugs when building WAVM with  gcc 8.2.1 and clang 7 (even if I revert this commit https://github.com/WAVM/WAVM/commit/69106c75c7eb544c8917643b10fa3eb4b42b2908, it compiled but got Segmentation Fault every time I try to run wavm-run). It's not really a big deal because setting CXX=g++-7 works for me. Just want to point it out in case someone runs into this problem.

**Comment by geloizi** [comment]
> The essential difference is that it "links" with the CMake targets exported from the WAVM package instead of with library files directly:
> `target_link_libraries(wavix WAVM::Logging WAVM::IR WAVM::WASM WAVM::Runtime)`

Could you explain how to link with IR library?

```
find_package(WAVM REQUIRED CONFIG PATHS ${PROJECT_SOURCE_DIR}/<path to wavm>})
target_link_libraries(wavm WAVM::WAVM WAVM::IR)
```

The linker replies:

```
/usr/bin/ld: cannot find -lWAVM::IR
```

**Comment by AndrewScheidecker** [comment]
I changed WAVM to create a single "WAVM" library that you can link with, instead of the individual library components. See the updated Wavix [CMakeLists.txt](https://github.com/WAVM/Wavix/blob/57ec640f5fa52ddf718d7a152c3bccb44cebb4e7/Wavix/CMakeLists.txt#L8):
> target_link_libraries(wavix WAVM::WAVM)

**Comment by geloizi** [comment]
Right! No need to link `IR` library explicitly. 

BTW, the build hasn't work for me until I set `LLVM_DIR`

```
set(LLVM_DIR ....../llvm6/lib/cmake/llvm)
```

**Comment by geloizi** [comment]
What is the right way of using WAVM as a static library "outside" of cmake build? Here is an example:

```
add_library(wavm STATIC wasm.h wasm.cpp)
target_link_libraries(wavm WAVM::WAVM)

add_executable(wasm-shell main.cpp)
#target_link_libraries(wasm-shell wavm) <-- this works as expected
target_link_libraries(wasm-shell ${PROJECT_SOURCE_DIR}/cmake-build-debug/libwavm.a) <-- WAVM symbols are unresolved
```

It seems `libwavm.a` isn't a "selfcontained" library. It still depends on the symbols from WAVM.

**Comment by AndrewScheidecker** [comment]
`target_link_libraries(my_target library_target)` in CMake does more than just add a `-llibrary_target.a` to the linker command line; it adds all the public or interface definitions, include paths, library dependencies, etc of `library_target` to `my_target`.
