### ISSUE TITLE
Run WAVM lock free? 

### ISSUE THREAD

**Issue by xrocket** [WAVM/WAVM#132]
I am trying to integrate WAVM with an asynchronous web framework, but there are mutexs here and there. I try edit the lock() and unlock() methods in Mutex.cpp, but it does not work. Is there anyway I can treat WAVM as single threaded application without locks or global states?

**Comment by AndrewScheidecker** [comment]
Can you elaborate on what doesn't work?

WAVM doesn't hold locks while non-WAVM code might be executing, with the possible exception of code in signal handlers. It doesn't seem like those locks could possibly be causing problems, but maybe I don't understand the problem.
