### ISSUE TITLE
Unsupported .eh_frame_hdr version

### ISSUE THREAD

**Issue by DennisMitchell** [WAVM/WAVM#133]
WAVM builds just fine on Fedora 29, but trying to execute any file with `wavm-run` shows the following error message.

```
libunwind: decodeEHHdr /opt/wasm/build/ThirdParty/libunwind/src/EHHeaderParser.hpp:61 - Unsupported .eh_frame_hdr version
```

The problem isn't present on Fedora 28. Please let me know what additional information I should provide.

**Comment by DennisMitchell** [comment]
After some updates to the OS, `wavm-run` segfaults now. I'm not sure if this related or not. Debugging output follows.

```
$ cat true.wast
(export "main" (func $main))
(func $main (result i32)
  i32.const 0
  return)
$ gdb -q /opt/wasm/prefix/bin/wavm-run
Reading symbols from /opt/wasm/prefix/bin/wavm-run...done.
(gdb) run true.wast
Starting program: /opt/wasm/prefix/bin/wavm-run true.wast
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff61c43ee in WAVM::LLVMJIT::Module::Module (this=0x4c3050, inObjectBytes=...,
    importedSymbolMap=..., shouldLogMetrics=<optimized out>)
    at /opt/wasm/build/Lib/LLVMJIT/LLVMModule.cpp:509
509                     function->mutableData->jitModule = this;
(gdb)
```

**Comment by AndrewScheidecker** [comment]
What LLVM are you linking with?

I don't see either of these problems on a fresh install/upgrade of Fedora 29, linking against LLVM 6 or 7 built from source.

**Comment by DennisMitchell** [comment]
I'm using the LLVM from Fedora's repos, currently llvm-7.0.0-2.

**Comment by DennisMitchell** [comment]
I tried installing the system packages `llvm6.0*` and passing `-DLLVM_DIR=/usr/lib64/llvm6.0/lib/cmake/llvm` to `cmake`, but that doesn't seem to change anything.

I'll try building LLVM from source later.

**Comment by AndrewScheidecker** [comment]
I tried using the system LLVM package (I had to install both `llvm-devel` and `llvm-static`), and it worked fine, so the llvm version/build is probably not the culprit.

**Comment by DennisMitchell** [comment]
OK, thanks.

I haven't actually tried on a fresh install (because DigitalOcean has no Fedora 29 image), but I did upgrade a fresh Fedora 28 install on DigitalOcean to Fedora 29.

After installing only `git llvm-* gcc-c++ zlib-devel` and running [this build script](https://github.com/TryItOnline/tiosetup/blob/master/languages/wasm), executing `wasm-run` on any valid `.wast` file still shows the .eh_frame_hdr version error.

After running `dnf update`, which updates kernel-core to 4.19.13-300.fc29, gobject-introspection to 1.58.3-1.fc29, libzstd to 1.3.8-1.fc29, and rsync to 3.1.3-5.fc29, I'm back to the segfault...

**Comment by DennisMitchell** [comment]
OK, this issue doesn't seem to be related to Fedora 29 after all.

I rebuild the VM with Fedora 28 and the exact same setup as the machines it is working on; I still get the .eh_frame_hdr version error (although it no longer segfaults).

Although I'm not sure how it would cause this issue, the only thing that's verifiably different between the VMs is the CPU. (The hypervisor might also be different, but I cannot check that.)

It's working on the ones with this CPU.

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
stepping	: 1
microcode	: 0x1
cpu MHz		: 2199.998
cache size	: 30720 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

It's not working on the ones with this one.

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
stepping        : 4
microcode       : 0x1
cpu MHz         : 2294.608
cache size      : 25344 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4589.21
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

**Comment by AndrewScheidecker** [comment]
Sorry for not following up on this.

I'm closing this issue as outdated; please reopen it if you're still running into it.
