### ISSUE TITLE
32-bit WASM guest on 64-bit host not possible?

### ISSUE THREAD

**Issue by zhangbo-miuNEST** [WAVM/WAVM#135]
Currently is 32-bit WASM guest on 64-bit host NOT possible?

Because the WASM instruction parameters such as MemoryImm/FunctionImm depend on "Uptr", while Uptr is 8-byte when compiling 64-bit hosts.

**Comment by AndrewScheidecker** [comment]
WAVM enforces the limits on number of memories and functions during serialization and validation, so the only effect of using `Uptr` instead of `U32` is to waste a little bit of memory.
