### ISSUE TITLE
WAVM::Runtime::loadPrecompiledModule doesn't work with USE_WINDOWS_SEH

### ISSUE THREAD

**Issue by PlasmaPower** [WAVM/WAVM#137]
It results in an error:
```
LLVM generated code references undefined external symbol: __C_specific_handler
```

However, setting USE_WINDOWS_SEH to 0 fixes the issue.

**Comment by AndrewScheidecker** [comment]
It works for me, on Linux or Windows, using `wavm-compile` and `wavm-run`.

Is this trying to load a precompiled module on Linux that was compiled by WAVM for Windows? The precompiled module is OS-specific, so that's not expected to work.

**Comment by PlasmaPower** [comment]
I am trying to compile and load on Windows. I'll see if I can reproduce it with the CLI.
