### ISSUE TITLE
How to access memory from the imported function?

### ISSUE THREAD

**Issue by chfast** [WAVM/WAVM#138]
Hi,

I'm adding an imported function using `DEFINE_INTRINSIC_FUNCTION`. Is there a way to access the wasm memory from within this function implementation? Can I also pass some additional external context to this function (e.g. a pointer to a struct created when the module was created)?

**Comment by AndrewScheidecker** [comment]
If you'll only have one WASM memory per thread (or globally), you can use the approach used by the Emscripten module:
- [Define a `thread_local` variable to pass the WASM memory to the intrinsic](https://github.com/WAVM/WAVM/blob/606d8dedd7a511652567771f22305458c1a11c77/Lib/Emscripten/Emscripten.cpp#L122)
- [Set the `thread_local` variable when instantiating your intrinsic module](https://github.com/WAVM/WAVM/blob/606d8dedd7a511652567771f22305458c1a11c77/Lib/Emscripten/Emscripten.cpp#L789)
- [Use the `thread_local` variable](https://github.com/WAVM/WAVM/blob/606d8dedd7a511652567771f22305458c1a11c77/Lib/Emscripten/Emscripten.cpp#L174) and the [`memoryRef` function from Runtime.h](https://github.com/WAVM/WAVM/blob/8b383e2432f83d0aac8d17e078a14f6ad8f9c715/Include/WAVM/Runtime/Runtime.h#L277) to access the WASM memory from your intrinsic.

> Can I also pass some additional external context to this function (e.g. a pointer to a struct created when the module was created)?

There isn't a way to do this (I've been able to make do with the `thread_local` trick for now). I've thought about adding an abstract `void*` parameter that you provide when instantiating an intrinsic module that is passed through as an argument to the intrinsic functions, but it would add a bit of overhead and complexity so I have been deferring it until I need it. Do you have a specific use case for that?

**Comment by chfast** [comment]
Hi @AndrewScheidecker,

Thanks very much for the answer. I'm asking about this case: https://github.com/ewasm/hera/blob/master/src/wavm.cpp.

We have an application specific context that is available to wasm modules via set of imported functions. Those functions obviously need to have at least a pointer to this application specific context data. And they also need to modify the memory.

So far we use a global container to keep track of the context. Not a thread safe, but good for the current version of the prototype. In long term, this is not suitable, but `thread_local` does not make it better, because `thread_local` will not work when the C++ code is loaded from Go.

I noticed that intrinsic functions have access to `contextRuntimeData` so I hoped there is an API I missed that allows to access the module's memory.

**Comment by AndrewScheidecker** [comment]
> I noticed that intrinsic functions have access to `contextRuntimeData` so I hoped there is an API I missed that allows to access the module's memory.

Yes, assuming the Compartment has exactly one memory created in it, you can use `getCompartmentRuntimeData(contextRuntimeData)->memoryBases[0]`. But there are a lot of caveats to that, and I think you're better off sticking with your current approach for now.

> Thanks very much for the answer. I'm asking about this case: https://github.com/ewasm/hera/blob/master/src/wavm.cpp.

Thanks for the example. I know this is a pain point right now, I'll try to think of a practical way to make it easier.

Some off topic feedback from skimming that code:

> `// Catching this here because apparently wavm doesn't necessarily checks bounds before allocation`

By default, this is true, but WAVM provides options that should prevent huge allocations when the input is invalid. FuzzWASM is an example of how to set these limits: https://github.com/WAVM/WAVM/blob/master/Test/fuzz/FuzzWASM.cpp#L18

> `// Note: wavm has an assertion to disallow multiple memory sections, but it is only enabled on debug builds.`

WAVM should reject modules with more than one total memory import/def during validation:

https://github.com/WAVM/WAVM/blob/master/Lib/IR/Validate.cpp#L858 and
https://github.com/WAVM/WAVM/blob/master/Lib/IR/Validate.cpp#L899

**Comment by AndrewScheidecker** [comment]
@chfast FYI I added `setUserData` and `getUserData` functions to the WAVM Runtime API. It allows associating a `void*` with any `Runtime::Object`. In WAVM's WASI implementation, it calls `setUserData(compartment, process)` on the Compartment, and then uses `process=getUserData(compartment)` in the intrinsic functions to find the WASI process info (including a pointer to the `Runtime::Memory`).
