### ISSUE TITLE
How can I generate user-defined module like threadTest when compiling by emcc

### ISSUE THREAD

**Issue by duanbing** [WAVM/WAVM#139]
I am writing a new external service from wasm, followed the approach of threadTest.
See this link for details: https://groups.google.com/forum/#!topic/emscripten-discuss/Fn6LPXJcp9Y
Thanks!

**Comment by AndrewScheidecker** [comment]
There's some very recent work in Clang/LLVM to add `import_module` and `import_name` attributes that can be used to specify the module and name of an imported function:
https://reviews.llvm.org/D57602
https://reviews.llvm.org/D57603
https://reviews.llvm.org/D57632

I assume that those will eventually work in Emscripten, but I'm not sure when.
