### ISSUE TITLE
Is WAVM reenterent?

### ISSUE THREAD

**Issue by geloizi** [WAVM/WAVM#141]
Would it be possible to call WAVM environment from different threads without locking? Let's assume the calling functions are stateless and don't require synchronisation.

**Comment by AndrewScheidecker** [comment]
Yes, that is the intent. You can, for example, pass multiple files to `RunTestScript` on the command line, and it will process the files in parallel in multiple threads.

**Comment by geloizi** [comment]
Sorry, my question wasn't clear enough. Is it possible to make calls **to the same context/compartment** from multiple threads? `RunTestScript` creates own context for each thread.

**Comment by AndrewScheidecker** [comment]
Compartment, yes; context, no.

Compartments can have multiple contexts, and each context corresponds to a thread in that compartment. A context stores its own copy of the value of each mutable global, which reflects how mutable globals in a browser WASM engine can't be shared between multiple workers; the WebAssembly module must be separately instantiated in each browser worker.

So it's not thread-safe to use the same Context in multiple threads. Since your functions are stateless, you should be able to just create a new Context for each thread you will be calling WASM code from.

**Comment by geloizi** [comment]
> Since your functions are stateless, you should be able to just create a new Context for each thread you will be calling WASM code from.

Although I do understand that this is how all js/wasm engines behave, this is not ideal. Each thread creates its own individual context and loads wasm binary into it. This makes serious impact on memory usage In case of an application with many threads.

**Comment by AndrewScheidecker** [comment]
> Although I do understand that this is how all js/wasm engines behave, this is not ideal. Each thread creates its own individual context and loads wasm binary into it. This makes serious impact on memory usage In case of an application with many threads.

WASM binaries are loaded into compartments, not contexts, so there's no need to load the WASM binary for each context. The memory cost of a Context is quite small compared to that of an OS thread: a little more than 4KB.

**Comment by geloizi** [comment]
> WASM binaries are loaded into compartments, not contexts, 

I see. So WAVM is quite different from js engines (v8 and spidermonkey) where compartments exist only inside contexts. Even initialization order is different:

```
// WAVM
compartment(Runtime::createCompartment())
context(Runtime::createContext(compartment))

// spider monkey
context = JS_NewContext()
compartment = new AutoCompartment(context)
```

**Comment by geloizi** [comment]
Confirmed! I modified `wasm-run` to make multiple contexts in different threads and all of them worked in parallel.

**Comment by CZDanol** [comment]
I'm a little baffled on how this applies on AssemblyScript. If I understand it correctly, the memory is shared across all contexts, right? The only thing not shared are globals. AssemblyScript has allocators that store information in globals, but ultimately they allocate stuff in the non-global memory. That would mean that the allocators from different threads work over the same overlapping memory pool?
