### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by chllcy** [WAVM/WAVM#142]
I did just like travis-build.sh. download and export LLVM_DIR.
build command like this:
mkdir debug
cd debug
cmake .. -DCMAKE_BUILD_TYPE=Debug \
         -DLLVM_DIR=${LLVM_DIR} \
         -DWAVM_ENABLE_RUNTIME=ON \
but it failed.
[ 77%] Linking CXX executable ../../bin/FuzzCompileModel
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::sys::DynamicLibrary::getPermanentLibrary(char const*, std::string*)'
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::string const&)'
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::DWARFContext::create(llvm::object::ObjectFile const&, llvm::LoadedObjectInfo const*, llvm::function_ref<llvm::ErrorPolicy (llvm::Error)>, std::string)'
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::RTDyldMemoryManager::getPointerToNamedFunction(std::string const&, bool)'
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::sys::getProcessTriple()'
/home/chen/github/wasm/WAVM/debug/Lib/LLVMJIT/libLLVMJIT.so: undefined reference to `llvm::EngineBuilder::selectTarget(llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::SmallVectorImpl<std::string> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [Test/fuzz/CMakeFiles/FuzzCompileModel.dir/build.make:89: bin/FuzzCompileModel] Error 1
make[1]: *** [CMakeFiles/Makefile2:1078: Test/fuzz/CMakeFiles/FuzzCompileModel.dir/all] Error 2

just 
cmake .. -DCMAKE_BUILD_TYPE=Debug \
         -DLLVM_DIR=${LLVM_DIR} \
it compiler success.

**Comment by AndrewScheidecker** [comment]
What version of LLVM did you download? The Travis CI build uses LLVM 6.

You can also look at the [Dockerfile](https://github.com/WAVM/WAVM/blob/master/Dockerfile), which builds WAVM in an Ubuntu 18.04 container using LLVM 6 installed from apt.

**Comment by chllcy** [comment]
> What version of LLVM did you download? The Travis CI build uses LLVM 6.
> 
> You can also look at the [Dockerfile](https://github.com/WAVM/WAVM/blob/master/Dockerfile), which builds WAVM in an Ubuntu 18.04 container using LLVM 6 installed from apt.

yes，I used LLVM6 on centos 7。I used g++ 7.3 compiler。if I need WAVM/Test/fuzz/configure-fuzzer-build.sh ？？

**Comment by AndrewScheidecker** [comment]
> docker is ok，but I want to know why failed on centos7.

I'm not sure, but I'm suspicious that it's using a system installation of LLVM instead of what you provided in the LLVM_DIR parameter. Can you double check the value of `LLVM_DIR` in `CMakeCache.txt`? e.g.

```
andrew@ubuntuserver:~/build/wavm$ cat CMakeCache.txt | grep LLVM_DIR
LLVM_DIR:UNINITIALIZED=~/build/llvm6/lib/cmake/llvm
```

**Comment by chllcy** [comment]
> > docker is ok，but I want to know why failed on centos7.
> 
> I'm not sure, but I'm suspicious that it's using a system installation of LLVM instead of what you provided in the LLVM_DIR parameter. Can you double check the value of `LLVM_DIR` in `CMakeCache.txt`? e.g.
> 
> ```
> andrew@ubuntuserver:~/build/wavm$ cat CMakeCache.txt | grep LLVM_DIR
> LLVM_DIR:UNINITIALIZED=~/build/llvm6/lib/cmake/llvm
> ```

[chen@localhost debug]$ cat CMakeCache.txt | grep LLVM_DIR
LLVM_DIR:UNINITIALIZED=/home/chen/wasm/lib/cmake/llvm
[chen@localhost debug]$ ll /home/chen/wasm/lib/cmake/llvm
total 364
-rw-r--r-- 1 root root 61634 Dec  6  2017 AddLLVM.cmake
-rw-r--r-- 1 root root   585 Oct 12  2015 AddLLVMDefinitions.cmake
-rw-r--r-- 1 root root  7780 Nov  4  2017 AddOCaml.cmake
-rw-r--r-- 1 root root  3470 Nov 30  2017 AddSphinxTarget.cmake
-rw-r--r-- 1 root root  3444 Dec 24  2017 CheckAtomic.cmake
-rw-r--r-- 1 root root  2291 Dec 24  2017 CheckCompilerVersion.cmake
-rw-r--r-- 1 root root   193 Oct 30  2017 CheckLinkerFlag.cmake
yes it's existed.

**Comment by AndrewScheidecker** [comment]
Closing as stale. If you're still having trouble with this, please reopen.
