### ISSUE TITLE
Question :is there any instructions of integrate wavm in java language project?

### ISSUE THREAD

**Issue by DreamWuGit** [WAVM/WAVM#143]
Hi, there 
Recently I want to use wavm to parse and run web assembly file , is it possible to integrate this with java project ? how many interfaces need to be implemented from java side ?  
Appreciate for any guidance or instructions here!

**Comment by AndrewScheidecker** [comment]
I'm not very familiar with Java, but you can call C APIs from Java, right? I think if https://github.com/WAVM/WAVM/issues/111 is implemented, then you should be able to use it from Java.

**Comment by DreamWuGit** [comment]
yes , Java can call C api,  I am wondering if the [#111 ](https://github.com/WAVM/WAVM/issues/111)  libwavm complete so far .

**Comment by AndrewScheidecker** [comment]
Have a look at #111 for some progress on a WAVM C API. If you have any issues using it from Java, feel free to open a new issue!
