### ISSUE TITLE
Windows/Mutex.cpp full of errors

### ISSUE THREAD

**Issue by kungfooman** [WAVM/WAVM#144]
Solution generated for 32bit VS2017 via CMake 3.13.1:

![image](https://user-images.githubusercontent.com/5236548/54523415-c2ce2c80-496f-11e9-957d-57aa9a880605.png)

**Comment by AndrewScheidecker** [comment]
https://github.com/WAVM/WAVM/commit/31e8a34a4e6f53a1586673cf74c7d76a20c63efd + https://github.com/WAVM/WAVM/commit/bc00863f58d8449149511791e26a9b1012268c88 should fix compiling for 32-bit Windows, and https://github.com/WAVM/WAVM/commit/b2ce135fe6ae3d60d8bef3bf45ce00b035054024 + https://github.com/WAVM/WAVM/commit/213562f43dc6e173ae15ceb55da6fe6a4294aae5 should fix the Intellisense squiggles.

**Comment by kungfooman** [comment]
Thanks alot for the quick fixing, it compiles and links fine now.
