### ISSUE TITLE
Are there any approaching to cache the moduleInstance when a module is executed many times?

### ISSUE THREAD

**Issue by duanbing** [WAVM/WAVM#145]
Basically, I have a large wasm binary file, I run it by WAVM, but the whole process is very slow. metrics info as below:
```
...
Emitted LLVM IR in 784.76ms (1304.862524 functions/s)
Optimized LLVM module in 10865.98ms (94.331140 functions/s)
Generated machine code in 35560.81ms (28.880107 functions/s)
...
```
So the first step to opt it is caching the object bytes after compiling the module. then it run much efficiently, metrics as below:
```
// no compiling process and no cost. and the follows metrics were added by myself.
...
RuntimeDyld loading in 143.92ms   // loadObject from objectBytes to llvm::ObjectFile
GDBRegister in 14.30ms     // add debug info to llvm::ObjectFile
function iterating in 84.82ms // fill addressToFunctionMap 
```
but it's still slow.    So I tried to cache the moduleInstance since then I don't have to transform the ObjectFile to real machine-target code. But How can I refresh the ModuleMemoryManager to run the moduleInstance again?

**Comment by duanbing** [comment]
Or Could we support llvm::ObjectCache in MCJIT?

**Comment by AndrewScheidecker** [comment]
I don't think `llvm::ObjectCache` avoids any of the object loading time you're measuring.

If you want to re-instantiate a module multiple times in a single process, you might be able to use `cloneCompartment`. Cloning the compartment conceptually makes a copy of all the modules, memories, and other objects instantiated in the compartment, but with special handling for module instances that re-uses the loaded machine code in the cloned module instance.

The LLVM RuntimeDyld object loader that WAVM uses could also be faster, but optimizing or replacing that is a big project.

**Comment by duanbing** [comment]
llvm::ObjectCache maybe not the best way, but will be an easier way, I agree with that.  Obviously, AOT is faster than JIT. So I am trying to caching machine code.  Do you think would it be very complex to do the "special handling" since I haven't known the memory management well?

**Comment by duanbing** [comment]
I cached the compartment, and when same module running again, I clone it by `cloneCompartment `, then I load the moduleIntance by its id. Still struggling to locate the sections which need "special handling"

**Comment by AndrewScheidecker** [comment]
> Still struggling to locate the sections which need "special handling"

I meant that cloning a compartment already has "special handling" for the machine code. See [`cloneModuleInstance`](https://github.com/WAVM/WAVM/blob/a2bb1439fe33db79c4b6c9afcccda174d0410c37/Lib/Runtime/Module.cpp#L476), which is called by `cloneCompartment`, and reuses the `LLVMJIT::Module` (which contains the machine code loaded from the object code).

**Comment by duanbing** [comment]
I see. There was an segments fault when running the cloned moduleInetance. I suspect the emsripten Instance need some special handing too.

**Comment by duanbing** [comment]
Thanks for your tips. my codes look as below:
```
static WAVM::HashMap<std::string, Compartment*> originalCompartmentMap;
static Emscripten::Instance *GEmscriptenInstance = nullptr;
int invokeFunction(void* modulePtr,char* debugName, char *functionName, char **argv, int argc)
{
	IR::Module* irModule = (IR::Module*)modulePtr;
	Runtime::ModuleRef module = compileModuleWithCache(irModule);

    Compartment* compartment = nullptr, *tmpCmpt = nullptr;
	Emscripten::Instance* emscriptenInstance = nullptr;
	ModuleInstance* moduleInstance = nullptr;

	if(originalCompartmentMap.contains(debugName)) {
		compartment = cloneCompartment(*(originalCompartmentMap.get(debugName)));
		moduleInstance = getModuleInstanceByName(compartment, debugName);  
		emscriptenInstance = GEmscriptenInstance;
	} else {
		compartment = Runtime::createCompartment();
		RootResolver rootResolver(compartment);
		emscriptenInstance = Emscripten::instantiate(compartment, *irModule);
		rootResolver.moduleNameToInstanceMap.set("env", emscriptenInstance->env);
		rootResolver.moduleNameToInstanceMap.set("asm2wasm", emscriptenInstance->asm2wasm);
		rootResolver.moduleNameToInstanceMap.set("global", emscriptenInstance->global);
		ModuleInstance* xchainServiceInstance = XChainService::instantiate(compartment, emscriptenInstance);
		rootResolver.moduleNameToInstanceMap.set("xchainservice", xchainServiceInstance);
		LinkResult linkResult = linkModule(*irModule, rootResolver);
		if(!linkResult.success)
		{
			Log::printf(Log::error,"link failed");
			return EXIT_FAILURE;
		}

		moduleInstance = instantiateModule(
				compartment, module, std::move(linkResult.resolvedImports), debugName);
		tmpCmpt = cloneCompartment(compartment);
		originalCompartmentMap.add(debugName, tmpCmpt);
		GEmscriptenInstance = emscriptenInstance;
	}

	if(!moduleInstance) { return EXIT_FAILURE; }
	Context* context          = Runtime::createContext(compartment);
	// Call the module start function, if it has one.
	Function* startFunction = getStartFunction(moduleInstance);
	if(startFunction) { invokeFunctionChecked(context, startFunction, {}); }
	Emscripten::initializeGlobals(context, *irModule, moduleInstance);

	Function* functionInstance;
	functionInstance
		= asFunctionNullable(getInstanceExport(moduleInstance, functionName));

	std::vector<Value> invokeArgs;
	std::vector<const char*> argStrings;
	argStrings.push_back(debugName);
	for (int i=0;i<argc;i++) {
		argStrings.push_back(argv[i]);
	};

	wavmAssert(emscriptenInstance);
	Emscripten::injectCommandArgs(emscriptenInstance, argStrings, invokeArgs);

    IR::ValueTuple functionResults = invokeFunctionChecked(context, functionInstance, invokeArgs);
    Log::printf(Log::debug,
            "%s returned: %s\n",
            functionName,
            asString(functionResults).c_str());

    return EXIT_SUCCESS;
}

```
I got ```libc++abi.dylib: terminating with uncaught exception of type PlatformException``` error, it occurred when executing ```    contextRuntimeData = (*invokeFunctionPointer)(function, contextRuntimeData);
```
  Need I refresh the Compartment.runtimeData since memory section was modified when the function was called firstly?

**Comment by duanbing** [comment]
the ```emscriptenMemory``` will grow linearly as the function called in the above source code.

**Comment by duanbing** [comment]
EOS[ wavm.cop](https://github.com/EOSIO/eos/blob/2232802dee4be1a3f6ca436edad64af3c45d7029/libraries/chain/webassembly/wavm.cpp)  seems similiar.

**Comment by AndrewScheidecker** [comment]
I don't see anything obviously wrong with your code. You should be using `Runtime::catchRuntimeExceptions` to handle any WASM runtime exceptions, though. That will prevent stuff like the WASM module accessing memory out-of-bounds from terminating the whole process.

I also think that it may be crashing inside the compiled WASM code instead of on that statement that calls the thunk. I rarely use XCode, but I think it does something similar to MSVC where if there's a trap while executing JITed code it will try to show you the C++ code that called it.

> Need I refresh the Compartment::runtimeData since memory and global section might be modified when the function was called firstly?

This shouldn't be necessary.

> Another approaching came to my mind is that I can split the invokeFunction into 2 : instantiate and invokeFunction. In Instantiate, create compartment and instantiate the specific moduleInstance, then store it in the global HashMap. In invokeFunction, I get the moduleInstance and invoke the function. it works. Does EOS do the optimization like this?

This is the first time I've looked at the EOS code, but it looks like it does something like that. But instead of using `cloneCompartment`, it just manually resets the memory and global state.

**Comment by duanbing** [comment]
Thanks for your tips.  I use vim and gdb,  so It's really hard to debug  when the dependent functions linked by ```dylib```.  but it's a big step forward for now.  I thought you are one of EOS developer members.

**Comment by duanbing** [comment]
Solved. you are right, it's ```crashing inside the compiled WASM code ``` from referencing an invalid pointer. 
Thanks.

**Comment by learnforpractice** [comment]
@duanbing Are you trying to sandbox some kind of vm with wavm? If so, let me know, I can share my knowledge with you.

**Comment by duanbing** [comment]
@learnforpractice  Yes, I am trying to run WebAssembly compiled from Go, C or rust in a standalone VM. Could we open another channel to communicate?   maybe email or IM.

**Comment by learnforpractice** [comment]
You 163 mail is over quota. You can contact me at learnforpractice@gmail.com, have a nice day!
