### ISSUE TITLE
Dynamic Linking

### ISSUE THREAD

**Issue by Shillaker** [WAVM/WAVM#147]
Hi Andrew,

Is there a way to implement dynamic linking with WAVM as described in the [wasm docs](https://webassembly.org/docs/dynamic-linking/)? I can create a new `dlopen` intrinsic function, have this create an `IR::Module` for the linked module, but I'm not sure how to then instantiate it. Would I need to somehow reuse the existing compartment with `Runtime::instantiateModule`, or is there some other way? If this is possible, then I assume `dlsym` would be a case of getting the exported function from the new module via `getInstanceExport`, adding it to the existing table and returning the relevant pointer.

Cheers

**Comment by AndrewScheidecker** [comment]
Yeah, it should work exactly as you described.

> Would I need to somehow reuse the existing compartment with `Runtime::instantiateModule`, or is there some other way?

You would reuse the existing compartment. WAVM shouldn't allow you to link module instances in different compartments together, although I don't think it verifies that right now.

**Comment by Shillaker** [comment]
Ok great, that's worked a treat, thanks! Keeping track of which handles refer to which module is a bit of a faff but other than that it's just a few calls to the WAVM runtime API.

When placing the imported functions into the existing table, is the best approach is to grow the table and insert the function pointer at the newly provisioned index? This will definitely work, but If the table is already big enough and has a spare slot, is it possible to put it there without growing? Sorry if I've completely misunderstood the way the tables work!

One note for anyone coming across this in future; if attempting this with Emscripten, it's essential to switch off any function pointer/ pointer cast emulation. With it switched on the extra indirection via `dynCall` is painful.

**Comment by AndrewScheidecker** [comment]
> When placing the imported functions into the existing table, is the best approach to grow the table and insert the function pointer at the newly provisioned index? This will definitely work, but If the table is already big enough and has a spare slot, is it possible to put it there without growing? Sorry if I've completely misunderstood the way the tables work!

Yeah, it should be fine to use indices that were previously allocated but not yet set. It should even be fine to reuse indices that are cleared by unloading a module. However, you'll have to coordinate allocation of indices between your runtime code and any WASM code that might use the new instructions to modify table slots (`table.set`, `table.copy`, `table.init`).
