### ISSUE TITLE
Dynamic linking - GOT

### ISSUE THREAD

**Issue by Shillaker** [WAVM/WAVM#150]
Hi Andrew,

I have a fairly simple issue that takes a lot of explaining. The issue is: I need to address globals (mutable and immutable) via normal linear memory offsets, and am not sure it's possible. The reason I need to do this is because of the new GOT approach to dynamic linking.

To dynamically link position-independent modules, external addresses are now shared via a "global offset table" (as described in the "planned changes" section of the [dynamic linking docs](https://github.com/WebAssembly/tool-conventions/blob/master/DynamicLinking.md#planned-changes)). When referencing functions, these offsets are table indices, and when referencing data they are linear memory offsets. I can populate the GOT with table indices for functions, but am struggling with the data offsets.

To clarify, if I'm dynamically linking Module A and Module B, Module A may define some global variable that Module B accesses via the GOT. This might look like the following:

```
# Module A

(export "myVar" (global $12))
...
(global $12  i32 (i32.const 1234))
...
global.get $12    # Standard global access, loads value 1234
```

```
# Module B (-fPIC)

(import "GOT.mem" "myVar" (global $4 (mut i32))) 
...
global.get $4    # Loads the address of the "myVar" global
i32.load           # Uses this address to load the value 1234
```

To make this work, the `GOT.mem` entry for `myVar` needs to be a normal linear memory offset accessible by the imported module. From what I can see, providing such offsets for globals isn't easily done in WAVM. Immutable globals are emitted directly as their initialized value and mutable globals are held outside of linear memory and accessed via `global.get` and `global.set`.

I think I can get around this for immutable values by creating a new region in linear memory, populating it with all the immutable values, then mapping these offsets in the GOT. I'm stumped on how to make this work for mutable globals though. Mutable GOT addresses need to be the same as those accessed via `global.set` and `global.get` to allow changes to be seen by all, but making this the case may require changing the default global behaviour.

Am I talking rubbish and in fact globals can be accessed via normal linear memory? If not do you have any ideas on how I can make this work?

Cheers

**Comment by AndrewScheidecker** [comment]
I think what the dynamic linking doc is describing is that the WASM globals are only used for addresses of C global variables. So e.g.:

```wat
;; Module A (-fPIC)

(global $__memory_base (import "env" "__memory_base") i32)
(global $myVarOffset (export "myVar") i32 (i32.const 0))
...
(data (global.get $__memory_base ) "\d2\04\00\00") ;; 1234
...
global.get $__memory_base    ;; Loads the base address of this module's data segment
global.get $myVarOffset      ;; Loads the offset of myVar in this module's data segment
i32.add                      ;; Computes the absolute address of myVar in memory.
i32.load                     ;; Loads the value of myVar from memory (1234).
```

```wat
;; Module B (-fPIC)

(import "GOT.mem" "myVar" (global $myVarAddress (mut i32))) 
...
global.get $myVarAddress     ;; Loads the address of the "myVar" global
i32.load                     ;; Loads the value of myVar from memory (1234).
```

So i32.load is always used to read the C ABI global variable. The module that defines it must allocate an address for it in linear memory.

I'm not sure if it's possible to mix a non-PIC module A with a PIC module B, but a PIC module A would import a `__memory_base` variable from the linker that tells it the base address for its static data segment. Then module A exports the offset of `myVar` relative to `__memory_base` (since immutable global initializer expressions are too limited to compute the absolute address), the dynamic linker computes the absolute address for `myVar`, and sets it to the mutable global that module B imports as `$myVarAddress`.

**Comment by Shillaker** [comment]
Thanks for the detailed response Andrew, sorry I'd totally misunderstood the gist of the original docs. That all makes sense and I've got it working 

You're right re. the absolute offset calculation in the dynamic linker. The GOT ends up full of absolute offsets into the single linear memory but these have to be worked out at link time relative to each module's `__memory_base` and `__table_base`. 

Thanks again!
