### ISSUE TITLE
Can a wasm module have two memory in total

### ISSUE THREAD

**Issue by gnanasekar-somanathan** [WAVM/WAVM#152]
can wasm module have one defined memory and one import memory from another module ?
Does wasm tools can generate such wasm module from C source which imports memory from another wasm module and also has its own memory defined?
And what would be needed to add such support in WAVM for resolving memory imports?

**Comment by AndrewScheidecker** [comment]
WAVM has most of the code to support modules with multiple memories (defined and/or imported). However:
- WAVM currently enforces the WebAssembly's spec requirement that a module has no more than 1 imported or defined memory; see https://github.com/WAVM/WAVM/blob/0c764ba09fd9aaa31645761001c64fdb4d13b4ae/Lib/IR/Validate.cpp#L886 and https://github.com/WAVM/WAVM/blob/0c764ba09fd9aaa31645761001c64fdb4d13b4ae/Lib/IR/Validate.cpp#L927
- The standard doesn't define load/store instructions to access memory objects other than index 0, and WAVM doesn't extend that.

It would be straightforward to add a flag to `IR::FeatureSpec` to enable non-standard behavior, use it to allow multiple memories, then extend the memory instructions with an immediate memory index.

However, you'd need to also modify Clang+LLVM+LLD to allow generate such modules with multiple memories and instructions to access them. I think that's a lot more complex than modifying WAVM.

**Comment by gnanasekar-somanathan** [comment]
thanks @AndrewScheidecker for detailed info.
