### ISSUE TITLE
Failed to run protobuf code

### ISSUE THREAD

**Issue by duanbing** [WAVM/WAVM#153]
Hi @AndrewScheidecker :
    When I run the code which uses `protobuf` to encode an object, I got the unreachable exception as below:

```
Generated stub for missing import env.___cxa_pure_virtual : func ()->()
Generated stub for missing import env.abortOnCannotGrowMemory : func i32->i32
Generated stub for missing import env._pthread_equal : func (i32, i32)->i32
Generated stub for missing import env._llvm_trap : func ()->()
nihao
Runtime exception: wavm.reachedUnreachable
Call stack:
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/libWAVM.dylib!unreachableTrap(WAVM::Runtime::ContextRuntimeData*)+43
  <unknown function>
  wasm!/Users/duanbing/Project/XXX/basic.wasm!<function #232>+19
  wasm!/Users/duanbing/Project/XXX/basic.wasm!<function #40>+15
  wasm!/Users/duanbing/Project/XXX/basic.wasm!<function #151>+10
  thnk!C to WASM thunk!(i32, i32)->i32+0
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/libWAVM.dylib!WAVM::Runtime::invokeFunctionChecked(WAVM::Runtime::Context*, WAVM::Runtime::Function*, std::__1::vector<WAVM::IR::Value, std::__1::allocator<WAVM::IR::Value> > const&)+358
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/./bin/wavm-run!std::__1::__function::__func<main::$_0, std::__1::allocator<main::$_0>, void ()>::operator()()+3446
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/libWAVM.dylib!WAVM::Platform::catchSignals(void (*)(void*), bool (*)(void*, WAVM::Platform::Signal, WAVM::Platform::CallStack&&), void*)+127
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/libWAVM.dylib!WAVM::Runtime::catchRuntimeExceptions(std::__1::function<void ()> const&, std::__1::function<void (WAVM::Runtime::Exception*)> const&)+49
  host!/Users/duanbing/Project/wasmproject/online-wavm/WAVM/output/./bin/wavm-run!main+713
```

c++ test code `basic.cpp`:

```
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>

#include "demo/basic.pb.h"
char g_buf[100] = "nihao";

int main(int argc, char* argv[]) {
    printf("%s\n", g_buf);
    pb::Response req;
    req.set_message("xxxxxx");
    return 0;
}
```

Compile it with command:
```
em++ -Os  -s ERROR_ON_UNDEFINED_SYMBOLS=0 -I. -I/usr/local/include  -o basic.wasm basic.cpp   ./xchain/basic.pb.cc -I./xchain -std=c++11  -L/usr/local/lib -lprotobuf-lite
```

proto file is `basic.proto`:

```
syntax = "proto3";
option optimize_for = LITE_RUNTIME;

package pb;

message Response {
  int32  status = 1;
  string message = 2;
  bytes  body = 3;
}
```
compiled with command:

```
protoc  -I. --cpp_out=./demo   basic.proto
```

and the protobuf version is 3.7 compiled with emcomfigure and emmake tools, special with flag `-DGOOGLE_PROTOBUF_NO_RTTI`  to disable rtti.

Did you test protobuf in WAVM before ?  Could you give me some tips ?

Thanks!

**Comment by AndrewScheidecker** [comment]
I haven't tried running protobuf with WAVM before.

Can you share the compiled .wasm or .wast file?

**Comment by duanbing** [comment]
Wast file: 
[basic.wast.txt](https://github.com/WAVM/WAVM/files/3158263/basic.wast.txt)

**Comment by duanbing** [comment]
This is wast file.  
[basic.wast.txt](https://github.com/WAVM/WAVM/files/3158347/basic.wast.txt)

**Comment by AndrewScheidecker** [comment]
Not sure why the call stack doesn't show it, but it's just failing when it calls the missing import stub for `_pthread_equal`. If I add this to Emscripten.cpp, it works:
```
DEFINE_INTRINSIC_FUNCTION(env, "_pthread_equal", I32, _pthread_equal, I32 a, I32 b)
{
	return a == b;
}
```

**Comment by duanbing** [comment]
Yes, solved for this case.  But how did you work it out?
Thanks!

**Comment by AndrewScheidecker** [comment]
If I run it on Windows, I see the import stub in the call stack instead of `<unknown function>`:
```
nihao
Runtime exception: wavm.reachedUnreachable
Call stack:
  host!WAVM.dll!unreachableTrap+41
  wasm!importStub!importStub: _pthread_equal+0
  wasm!C:\Dropbox\Temp\WAVM\basic.wast!<function #231>+17
  ...
```

**Comment by duanbing** [comment]
Thanks, @AndrewScheidecker  I will take a look at why the stack is not completed

**Comment by duanbing** [comment]
Hi Andrew: 
    I have some progress of losing the stack info to share.  when I compiled WAVM in my mac, I got a warning: 
```
ld: warning: could not create compact unwind for _forkedStackTrampoline: does not use RBP or RSP based frame
```
I didn't pay any attention to this warning.  So when I look back the function `captureCallStack`, where unwind library is used to fetch the trace stack when exceptions happened.  so I guess this issue is relevant to the register.

In `captureCallStack`,  function unw_get_reg get the IP from the register, then `describeInstructionPointer`  will read the DL_info from the IP, but we cann't always get the right DL_info from the IP which stored in the register, and I got none after calling `dlerror` to trap the error after `dladdr`.

So, bring all those together, I guess there are wrong with the register.  so I use another function `unw_get_proc_info` to get the IP,  finally get the right call stack.

the fix is here: https://github.com/duanbing/WAVM/commit/c0e0291c77457f326932db67a98a239563f5a228

I am still now sure if I am right, but it works.

**Comment by AndrewScheidecker** [comment]
The `unw_get_proc_info` change will abandon any information about where in the function execution was, but it's helpful to see that it fixed the problem.

`dladdr` doesn't need to work for JIT compiled functions (like the import stub): `LLVMJIT::getFunctionByAddress` should find it, so `Runtime::describeInstructionPointer` will never even call `dladdr` via `Platform::describeInstructionPointer`.

I think the root problem is that when the import stub is compiled, the call to the WAVM unreachable trap function is not followed by any more code, since LLVM doesn't expect it to return. However, that means that the return address points past the end of the function, so `LLVMJIT::getFunctionByAddress` has trouble finding it.

**Comment by duanbing** [comment]
Yes, you are right, the reg_ip is equal to the unw_proc.end_ip (e.g. start_ip=4528803872 reg_ip=4528803888 end_ip=4528803888) for unreachable function, has nothing to the register.  
but I still have no idea why it happened in MacOS, not in your WinOS(this is why I tried to fix it under a macro). 

So maybe a better fixing is to check if the reg_ip is equal to end_ip and if so push the start_ip into the CallStack?   
like https://github.com/duanbing/WAVM/commit/b84dbc7007aed8ae942b83c4b9a8b0baf6c8a8e7.

**Comment by AndrewScheidecker** [comment]
[This commit](https://github.com/WAVM/WAVM/commit/fcbdc5619afdc8e4ecf2472374849ed60890b1bb) should improve things a bit: it just applies a -1 offset to return addresses in the call stack. This means they won't point to exact instruction boundaries, but is good enough to map the machine code pointer back to a WASM function + instruction index.

**Comment by duanbing** [comment]
Thanks for your solution.
