### ISSUE TITLE
Profiling wasm code

### ISSUE THREAD

**Issue by Shillaker** [WAVM/WAVM#154]
Hi Andrew,

I'm trying to use callgrind to generate a call graph for a wasm module executing inside WAVM. The result picks up the right function names for intrinsic functions (and obviously the outer runtime), but not the functions inside the module. These are shown as numbers like `0x000000000e5d1130`. 

The functions in question are loaded via `LLVMJIT::loadModule()` and I think I need to fiddle with something in the JIT configuration to get it to work. I can see the debug info is present in the object file that gets loaded, and assume I need to modify the loading code in the `Module` constructor, but can't work out what to change to get the names to pass through.

Do you have any ideas on how I might get this to work? If not do you think there's any other profiling tool that might be a better fit for generating a call graph?

Cheers

**Comment by AndrewScheidecker** [comment]
From googling, I couldn't find anything about notifying Callgrind about symbols for new code.

[WAVM calls](https://github.com/WAVM/WAVM/blob/0c764ba09fd9aaa31645761001c64fdb4d13b4ae/Lib/LLVMJIT/LLVMModule.cpp#L203) `llvm::sys::Memory::InvalidateInstructionCache`, [which eventually calls](https://github.com/llvm/llvm-project/blob/2946cd701067404b99c39fb29dc9c74bd7193eb3/llvm/lib/Support/Valgrind.cpp#L42) [`VALGRIND_DISCARD_TRANSLATIONS`](http://valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq).

WAVM also [uses the GDB hook to register debug symbols for JIT modules](
https://github.com/WAVM/WAVM/blob/0c764ba09fd9aaa31645761001c64fdb4d13b4ae/Lib/LLVMJIT/LLVMModule.cpp#L477).

If anybody knows how to get Valgrind to use the debug info for the JITed code, please let me know!

**Comment by Shillaker** [comment]
Hi Andrew, thanks for the quick response. I spent a while wrestling with Valgrind but just couldn't work out what's wrong. As far as I can tell the debug info is generated properly and written out to the object file, which then gets interpreted properly at runtime. From the Valgrind docs it sounds like `VALGRIND_DISCARD_TRANSLATIONS` should do the trick, but I also tried `smc-check=all`, `keep-debuginfo` and `allow-mismatched-debuginfo`, all to no avail.

One small point on which I may be mistaken is that I'm not actually sure `InvalidateInstructionCache` does get called. It looks like the `invalidateInstructionCache` call on a `RTDyldMemoryManager` gets invoked by the default `finalizeMemory` method (as mentioned [here](http://llvm.org/doxygen/classllvm_1_1SectionMemoryManager.html#a64835973f93c4f018aa377870e15ee97) in the docs for the `SectionMemoryManager` superclass), but the `finalizeMemory` method is overridden in WAVM. I _think_ the call needs to be added to `reallyFinalizeMemory`, although I made the change and it didn't seem to influence things so I may be wrong.

As an alternative I have had some success with `perf`. There is a `PerfJITEventListener` similar to the GDB one that's already used in WAVM (described [here](https://lwn.net/Articles/633846/)). It requires a custom build of LLVM with `LLVM_USE_PERF` switched on, but once that's done and the hooks added to `LLVMModule` alongside the GDB ones, it works fine. The names that get used are of the form `functionDef123` and `functionImport123`, so I needed to do some fiddling with `IR:DisassemblyNames` to work out what they link back to in the source.

Anyway, thanks again for your help, very much appreciated.

**Comment by AndrewScheidecker** [comment]
> One small point on which I may be mistaken is that I'm not actually sure InvalidateInstructionCache does get called. It looks like the invalidateInstructionCache call on a RTDyldMemoryManager gets invoked by the default finalizeMemory method (as mentioned here in the docs for the SectionMemoryManager superclass), but the finalizeMemory method is overridden in WAVM. I think the call needs to be added to reallyFinalizeMemory, although I made the change and it didn't seem to influence things so I may be wrong.

Thanks, I made `reallyFinalizeMemory` call it: https://github.com/WAVM/WAVM/commit/cb2dfac8ec021ae3180307b0be7e7429a23e707c

It shouldn't make any difference on x86, but it would be necessary for any future support for ARM or other ISAs.

> The names that get used are of the form functionDef123 and functionImport123, so I needed to do some fiddling with IR:DisassemblyNames to work out what they link back to in the source.

Those symbols (`functionDef123` and `functionImport123`) are used to bind imported functions to the appropriate pointer on load, and to find function definitions in the loaded object, so it's tricky to use user-provided strings for them. Ideally those symbols wouldn't be visible to the user, but maybe that breaks too much existing tooling.

**Comment by Shillaker** [comment]
Ok great, cheers! Yes I noticed that those names were fairly integral so didn't try fiddling with them. As long as they emerge in the perf output with something that can be traced back to the source then that's more than enough. One alternative could be injecting the "right" name into the data just before it's sent to the JIT event listener, but that also seems like overkill for now.

Thanks again.
