### ISSUE TITLE
Can this VM be embedded into a C++ app to provide scripting capabilities?

### ISSUE THREAD

**Issue by gamagan** [WAVM/WAVM#157]
I have a custom scripting language for which I'm looking for a VM. I also have a game engine written in C++. Can this WAVM be integrated into the game engine such that it can provide scripting capabilities? 

Or, is this VM made to be ran stand-alone from the command line, like a Perl script?

**Comment by AndrewScheidecker** [comment]
Yes, most of WAVM's functionality is in a library that you could use in a game engine for scripting.

**Comment by mrpre** [comment]
@AndrewScheidecker Is there any sample that describe how to load WAVM and load `.wasm` file in a C/C++ process?

**Comment by AndrewScheidecker** [comment]
> Is there any sample that describe how to load WAVM and load .wasm file in a C/C++ process?

If you're using CMake, it should be pretty straightforward to link with WAVM. Here's an example of a different CMake project importing WAVM as a package and linking with it: https://github.com/WAVM/Wavix/blob/master/Wavix/CMakeLists.txt. It's possible to use it from a project that isn't built by CMake, but I don't have an example of that.

The best example of how to use the WAVM API to load and run a .wasm file is probably the source for the `wavm-run` program: https://github.com/WAVM/WAVM/blob/master/Programs/wavm-run/wavm-run.cpp

In general, everything in the WAVM/Include directory is a public API that is accessible by linking against libWAVM.so/WAVM.dll.

**Comment by mrpre** [comment]
@AndrewScheidecker How to call function defined in host env ?   
I'm writting an example
`ef` is exported and the `inif` is defined in host env, how cloud i import `inif` ?    


```
cat tmp.c 

#include <stdio.h>
extern void inif(void);
int ef()
{
        inif();
        printf("inif\n");
        return 1;
}
```  
compile like this:
`emcc tmp.c -s "EXPORTED_FUNCTIONS=['_ef']" -s ERROR_ON_UNDEFINED_SYMBOLS=0 -o 1.wasm`

Then I modified the `wavm-run.cpp` and just add an function in the head of it:  
```
void inif()
{
        std::cout<<"in if"<<std::endl;
}
``` 
But I found `1.wasm` didn't find the function `inif`.  
```
wavm-run 1.wasm -f _ef 
```

```
root@iZrj97ibqurmwnu9mj5htdZ:~/wavm/WAVM# wavm-run 1.wasm -f _ef
Generated stub for missing import env.nullFunc_iidiiii : func i32->()
Generated stub for missing import env.nullFunc_jiji : func i32->()
Generated stub for missing import env._inif : func ()->()
Generated stub for missing import env.abortOnCannotGrowMemory : func i32->i32
Generated stub for missing import env.setTempRet0 : func i32->()
Runtime exception: wavm.reachedUnreachable
Call stack:
  host!/root/wavm/WAVM/libWAVM.so!<unknown>
  wasm!importStub!importStub: _inif+0
  wasm!1.wasm!<function #4>+15
  thnk!C to WASM thunk!()->i32+0
  host!/root/wavm/WAVM/libWAVM.so!WAVM::Runtime::invokeFunctionUnchecked(WAVM::Runtime::Context*, WAVM::Runtime::Function*, WAVM::IR::UntaggedValue const*)+350
  host!/root/wavm/WAVM/libWAVM.so!WAVM::Runtime::invokeFunctionChecked(WAVM::Runtime::Context*, WAVM::Runtime::Function*, std::vector<WAVM::IR::Value, std::allocator<WAVM::IR::Value> > const&)+493
  host!./a.out!<unknown>
  host!./a.out!<unknown>
  host!/root/wavm/WAVM/libWAVM.so!WAVM::Platform::catchSignals(void (*)(void*), bool (*)(void*, WAVM::Platform::Signal, WAVM::Platform::CallStack&&), void*)+214
  host!/root/wavm/WAVM/libWAVM.so!WAVM::Runtime::unwindSignalsAsExceptions(std::function<void ()> const&)+57
  host!/root/wavm/WAVM/libWAVM.so!WAVM::Runtime::catchRuntimeExceptions(std::function<void ()> const&, std::function<void (WAVM::Runtime::Exception*)> const&)+31
  host!./a.out!<unknown>
  host!/lib/x86_64-linux-gnu/libc.so.6!__libc_start_main+230
  host!./a.out!<unknown>

Aborted
```  
Is there any possibility to load `inif` conveniently like `printf` (why we needn't treat `printf` specially , seems that i needn't import `printf`)?

**Comment by AndrewScheidecker** [comment]
I'm closing this as the original question has been answered.

@mrpre Sorry for missing this last question. If it's not answered by #180, please follow up there or in a new issue.
