### ISSUE TITLE
Same code, different memory?

### ISSUE THREAD

**Issue by bofh69** [WAVM/WAVM#177]
I'm building a simulator for an embedded system written in C. We try to simulate 2000 devices in realtime.

Our current simulator loads the C code once, then it runs the code for one tick (just one function call really), it makes a backup of the text&bss sections, then copies the next instance's memory in and runs it for a tick and so on. This makes the simulator limited by the memory bandwidth since all the memory has to be copied in and out for every device & tick.

I tried changing it to fork different processes after the loading the instance, but then the context switches limits the system to less than 400 simulated devices if we want to run in realtime.

If we instead would load the code once per device, our instruction cache would be the limiting factor as we would have 2000 copies of the same (~300kB) code.

I had the idea of instead compiling the code for WASM and there have different memory contexts for each device, thus keeping the same code, but different data.

Would that be possible with WAVM or is the JIT:ed code pointing to global memory directly?

**Comment by AndrewScheidecker** [comment]
WAVM does support that via `Runtime::cloneCompartment`: https://github.com/WAVM/WAVM/blob/77b69d194321a26ece1130c7c2685b30f70a8ccc/Include/WAVM/Runtime/Runtime.h#L450

`cloneCompartment` conceptually makes a copy of a compartment and all the runtime objects it contains (functions, memories, etc). However, it does not literally copy the functions, and the same machine code is shared between the original compartment and its clone.

When you call a function, you must specify the compartment it will run in (and thus which memory it will access) by passing a Context object as an argument.

**Comment by bofh69** [comment]
@AndrewScheidecker sound like it will be a perfect fit for out use case then. Thank you!
