### ISSUE TITLE
Support "assert_return_arithmetic_nan" and "assert_return_canonical_nan" for SIMD

### ISSUE THREAD

**Issue by Honry** [WAVM/WAVM#187]
Tests:
```
(assert_return_canonical_nan (invoke "f32x4.add" 
(v128.const f32x4 -0x0p+0 -0x0p+0 -0x0p+0 -0x0p+0) 
(v128.const f32x4 –nan –nan –nan -nan)))
(assert_return_arithmetic_nan (invoke "f32x4.add"
(v128.const f32x4 -0x0p+0 -0x0p+0 -0x0p+0 -0x0p+0)
(v128.const f32x4 -nan:0x200000 -nan:0x200000 -nan:0x200000 -nan:0x200000)))
```
Errors:
```
f32x4_arith.wast:5:2: expected canonical float NaN but got v128.const i32x4 0xffc00000 0xffc00000 0xffc00000 0xffc00000
(assert_return_canonical_nan (invoke "f32x4.add" 
(v128.const f32x4 -0x0p+0 -0x0p+0 -0x0p+0 -0x0p+0) 
(v128.const f32x4 -nan -nan -nan -nan)))
 ^
f32x4_arith.wast:6:2: expected float NaN but got v128.const i32x4 0xffe00000 0xffe00000 0xffe00000 0xffe00000
(assert_return_arithmetic_nan (invoke "f32x4.add" 
(v128.const f32x4 -0x0p+0 -0x0p+0 -0x0p+0 -0x0p+0)
(v128.const f32x4 -nan:0x200000 -nan:0x200000 -nan:0x200000 -nan:0x200000)))
 ^
Testing failed with 2 error(s) 
```

@AndrewScheidecker, need your support. :)

**Comment by AndrewScheidecker** [comment]
How should it distinguish whether the returned value is `f64x2` and `f32x4`?

I could add a suffix to the assertion:
`(assert_return_arithmetic_nan_f32x4 (invoke ...))`

Or I could require a type annotation if the invoke returns a `v128`:
`(assert_return_arithmetic_nan f32x4 (invoke ...))`

Does it matter that it wouldn't help with cases where the result is expected to only contain arithmetic/canonical NaNs in a subset of lanes?

[These sqrt tests](https://github.com/WAVM/WAVM/blob/master/Test/wabt/wabt_simd_unary.wast#L149) imported from wabt currently return different NaNs on X86 and AArch64, but only expects canonical NaNs in a subset of lanes, and so would not benefit from an `assert_return_canonical_nan` that simply asserts that all lanes are canonical NaNs.

Another option would be to allow the assertion to use an extract_lane instruction:

```
(assert_return_canonical_nan (f32x4.extract_lane 0 (invoke "f32x4_sqrt_0")))
(assert_return_canonical_nan (f32x4.extract_lane 1 (invoke "f32x4_sqrt_0")))
(assert_return               (f32x4.extract_lane 2 (invoke "f32x4_sqrt_0")) (f32.const 2.0))
(assert_return               (f32x4.extract_lane 3 (invoke "f32x4_sqrt_0")) (f32.const 3.0))
```

@tlively, @arunetm, @dtig, @rossberg, would appreciate your thoughts.

**Comment by tlively** [comment]
Hmm, testing via extract_lane is probably reasonable in the case of different lanes. It doesn’t seem worth doing anything more complex for that. For homogenous results I think adding a type suffix to the assertion would be fine if that’s the simplest solution.

**Comment by Honry** [comment]
+1 to @tlively. :)

**Comment by AndrewScheidecker** [comment]
https://github.com/WAVM/WAVM/commit/e59418bac8915e308f2d8d080d699a2c1277cb77 adds `assert_return_canonical_nan_f32x4`, `assert_return_canonical_nan_f64x2`, `assert_return_arithmetic_nan_f32x4`, and `assert_return_arithmetic_nan_f64x2`.

**Comment by Honry** [comment]
Verified! Thank you @AndrewScheidecker!

**Comment by rossberg** [comment]
Wouldn't `assert_return_*_nan f32x4` be more consistent with `v128.const` syntax? This assertion is basically a disjunction of multiple `assert_return ... (v128.const f32x4 nan:0xXXX)`.

**Comment by tlively** [comment]
@rossberg can you elaborate on your point about the disjunction? My impression is that `assert_return_*_nan_fNxM` is a conjunction of assertions that each lane is the correct kind of NaN.

Also, I'm not sure there is much benefit to being consistent with the `v128.const` syntax here. `v128.const` is unique in that there are multiple text formats mapping to the same underlying instruction, whereas `assert_return_*_nan_f32x4` is a different assertion from `assert_return_*_nan_f64x2`.

**Comment by rossberg** [comment]
It's a disjunction over all possible nan representations. For example,
```
(assert_return_canonical_nan (...))
```
where `(...)` has type `f64`, is a disjunction of the following two assertions:
```
(assert_return (...) (f64.const nan:0x0))
(assert_return (...) (f64.const nan:0x8000000000000))
```
In a similar vein,
```
(assert_return_canonical_nan f64x2 (...))
```
where `(...)` has type `v128`, is a disjunction over all of
```
(assert_return (...) (v128.const f64x2 nan:0x0 nan:0x0))
(assert_return (...) (v128.const f64x2 nan:0x0 nan:0x8000000000000))
(assert_return (...) (v128.const f64x2 nan:0x8000000000000 nan:0x0))
(assert_return (...) (v128.const f64x2 nan:0x8000000000000 nan:0x8000000000000))
```
and so on.

In fact, the syntax should probably be
```
(assert_return_*_nan (...) f64x2)
```
to match the style of other assertions, where the specification of the result always goes last.

**Comment by AndrewScheidecker** [comment]
>In fact, the syntax should probably be
>```
>(assert_return_*_nan (...) f64x2)
>```

It's true that `assert_return` places its expected return value at the end, but `assert_return_*_nan` moves it to the beginning, and I find it hard to read when I put the type annotation at the end. e.g. from `simd_f32x4_arith.wast`:
```
(assert_return_canonical_nan (invoke "f32x4.add" (v128.const f32x4 inf inf inf inf)
                                                 (v128.const f32x4 -inf -inf -inf -inf))
                             f32x4)
```

I'm ambivalent about `assert_return_*_nan_f32x4` vs `assert_return_*_nan f32x4`.

**Comment by rossberg** [comment]
@AndrewScheidecker, that's fair, however, for better or worse that's what we already have.

That said, better formatting helps:
```
(assert_return_canonical_nan
  (invoke "f32x4.add" (v128.const f32x4 inf inf inf inf) (v128.const f32x4 -inf -inf -inf -inf))
  f32x4
)
```

(FWIW, formatting style that produces arbitrary indentation through vertical alignment with middle-of-the-line characters is horrible for many reasons. But I digress.)

**Comment by Honry** [comment]
@AndrewScheidecker, @rossberg, so, do we have an agreement here?

**Comment by rossberg** [comment]
@Honry, not sure. @AndrewScheidecker, are you fine with `(assert_return_*_nan (...) f64x2)` for the sake of overall consistency?

**Comment by Honry** [comment]
@AndrewScheidecker, friendly ping. :)

**Comment by AndrewScheidecker** [comment]
I'm fine either way. However, I think the right place to decide it is probably with an issue in the WebAssembly/simd repo rather than here, as there may be people who are interested do not follow this repo.

**Comment by abrown** [comment]
@AndrewScheidecker, done: https://github.com/WebAssembly/simd/issues/137. Can you tag there whoever else you think would have an opinion?
