### ISSUE TITLE
Add C++ API from https://github.com/WebAssembly/wasm-c-api

### ISSUE THREAD

**Issue by jplevyak** [WAVM/WAVM#192]
There is a C++ version also at https://github.com/WebAssembly/wasm-c-api.

**Comment by AndrewScheidecker** [comment]
I'm not currently planning to implement the wasm-c-api C++ API. It will never replace WAVM's native API, so it would be necessary to maintain the native C++ API, the C API, and the cross-engine C++ API. I'd rather work on improving the cross-engine C API.

IMO wasm-c-api should just define a cross-engine C API, and API clients can use a C++ wrapper around it if they desire.
