### ISSUE TITLE
Question: How do I return a string from a native host function?

### ISSUE THREAD

**Issue by renjipanicker** [WAVM/WAVM#200]
I would like to generate a UUID natively in my app. What is the best way to return the generated value back to the WASM module?
This is an example of the problem (in WASM code) I am trying to solve:
```
extern "C" int uuidgen(char* buf, const size_t& buflen);

int main() {
    char buf[16];
    uuidgen(buf, 16);
}
```
I tried reading up on anyref but didn't seem to get anywhere. Any help would be appreciated.
Thanks.
EDIT: I am compiling the C++ code using clang++-8 in wasi-sdk.

**Comment by AndrewScheidecker** [comment]
You need to do something like this:
```
inline WASI::Process* getProcessFromContextRuntimeData(
    Runtime::ContextRuntimeData* contextRuntimeData)
{
    return (WASI::Process*)Runtime::getUserData(
        Runtime::getCompartmentFromContextRuntimeData(contextRuntimeData));
}
WAVM_DEFINE_INTRINSIC_FUNCTION(mymod,
                               "uuidgen",
                               I32,
                               mymod_uuidgen,
                               U32 bufferAddress,
                               U32 bufferLengthAddress)
{
    WASI::Process* process = getProcessFromContextRuntimeData(contextRuntimeData);
    Memory* memory = WASI::getProcessMemory(process);

    U32& numBufferBytes = memoryRef<U32>(memory, bufferLengthAddress);
    U8* buffer = memoryArrayPtr<U8>(memory, bufferAddress, numBufferBytes);

    // generate the UUID in buffer
}
```

That `getProcessFromContextRuntimeData` function is copied from the WASI runtime, but I will add that to the WASI module API so you don't need to copy it.

`contextRuntimeData` is a hidden parameter to intrinsic functions that is passed in by the WASM code so the intrinsic function can figure out which `Context`+`Compartment` it's being called from.

**Comment by renjipanicker** [comment]
I'm almost there! One small issue - WASI::getProcessMemory() expects a shared_ptr(), but I can't create one because the implementation of WASI::Process is inside WASI/WASIPrivate.h.

I suspect getProcessMemory() will have to take a raw pointer, since it will be tougher to have Runtime::getUserData() return a shared_ptr()?

**Comment by AndrewScheidecker** [comment]
Good point: see https://github.com/WAVM/WAVM/commit/654658d0727314da85724cc9254ee66e46be8270

**Comment by renjipanicker** [comment]
This worked brilliantly! Thanks for the quick turnaround, Andrew!
