### ISSUE TITLE
Question: How to allocate memory in host?

### ISSUE THREAD

**Issue by renjipanicker** [WAVM/WAVM#201]
Hi,

I would like to implement a native function in the host to read and parse a JSON file, and return the parsed data to the WASM module. Something like:

```
extern "C" json_node* parseJSON(const char* filename);

int main() {
    json_node* root = parseJSON("config.json");
}
```
My problem is - how do I allocate memory on the host-side code in which I can store the parsed data?

I discovered Runtime::growMemory() but couldn't find any documentation on how it should be used. The only code I found where it is being used is in LLVMJIT and the C API.

Any help on this would be appreciated. Thanks!

**Comment by AndrewScheidecker** [comment]
`Runtime::growMemory` is similar to the `memory.grow` WebAssembly instruction: it works with WASM pages (64KiB) and probably isn't what you're looking for.

The Emscripten ABI has a way to do this: take a look at `Emscripten::dynamicAlloc`. However, I think the latest Emscripten ABI (which WAVM doesn't yet support) exports an equivalent function from the WASM module for host functions to call.

Why do you want to do the JSON parsing in host code? I think in most cases you will be better off just using the WASI APIs for file I/O, and read/parse the JSON file from WASM code.

**Comment by renjipanicker** [comment]
I was hoping to reuse some existing libraries, but if there is no clean way to do it, I guess I will go with your suggestion to parse it WASM-side. Thanks Andrew!
