### ISSUE TITLE
Error during wavm run command - unhandled SIGSEGV - Aborted (core dumped)

### ISSUE THREAD

**Issue by tpmccallum** [WAVM/WAVM#218]
I am getting the following error
```
unhandled SIGSEGV
Call stack:
  /usr/lib/libWAVM.so.0!WAVM::Errors::fatalfWithCallStack(char const*, ...)+134
  /usr/lib/libWAVM.so.0+11823831
  /lib/x86_64-linux-gnu/libpthread.so.0+75919
Aborted (core dumped)
```
I am using the following command to run my wasm file.
```
wavm run --abi=bare a.wasm
```
The environment on my machine seems to be set up properly because the wavm examples can execute without any issues i.e. 
```
wavm run examples/helloworld.wast 
Hello World!
```
I tried with the simplest code, as shown below. But I always get the same error (as error as pasted above)
Original Rust
```
#[no_mangle]
pub extern fn main() -> u32 {
    1 + 1
}
```
Compiled to Wat
```
(module
  (type $t0 (func (result i32)))
  (func $main (export "main") (type $t0) (result i32)
    i32.const 2)
  (table $T0 1 1 anyfunc)
  (memory $memory (export "memory") 17))
```

**Comment by tpmccallum** [comment]
I thought that using `wasm32-wasi` instead of `wasm32-unknown-unknown` would produce a better result. However, I am also getting the same error with wasm32-wasi.

```
wavm run target/wasm32-wasi/release/adding_lib.wasm
```

```
unhandled SIGSEGV
Call stack:
  /usr/lib/libWAVM.so.0!WAVM::Errors::fatalfWithCallStack(char const*, ...)+134
  /usr/lib/libWAVM.so.0+11823831
  /lib/x86_64-linux-gnu/libpthread.so.0+75919
Aborted (core dumped)
```

**Comment by tpmccallum** [comment]
I am trying to run Rust code as WASM in this stand-alone WAVM as apposed to using a runtime like wastime and/or lucet etc.

**Comment by AndrewScheidecker** [comment]
I'll fix the crash, thanks for reporting.

The problem is that the bare ABI doesn't have any logic to figure out which function to call if it's not specified on the command line. You can work around it for now by running `wavm run --abi=bare --function=main ...`.

**Comment by tpmccallum** [comment]
Brilliant! Thanks @AndrewScheidecker, I am no longer getting the error.
