### ISSUE TITLE
Accessing console/terminal output and file system

### ISSUE THREAD

**Issue by tpmccallum** [WAVM/WAVM#219]
Hi,
I have the following two Rust programs which both compile to WASM and run, on WAVM.

**file_system.rs**
```
use std::fs::File;
use std::io::prelude::*;
#[no_mangle]
pub extern fn main() -> std::io::Result<()> {
    let mut file = File::create("foo.txt")?;
    file.write_all(b"Hello, world!")?;
    Ok(())
}
```
**console.rs**
```
#[no_mangle]
pub extern fn main() {
    let z: i32 = 1 + 1;
    println!("The value of x is: {}", z);
}
```
Both are compiled successfully using both build targets `wasm32-unknown-unknown` & `wasm32-wasi` (I am also using crate-type of `cdylib` in the Cargo.toml to these are essentially libraries)
```
[lib]
name = "myprogram_lib"
path = "src/myprogram.rs"
crate-type =["cdylib"]
```

They are being executed using the following command format
```
wavm run --abi=bare --function=main ~/myprogram_name/target/wasm32-unknown-unknown/release/myprogram_lib.wasm
```
The file_system.rs program produces the following errors
```
Failed to link module:
Missing import: module="wasi_unstable" export="fd_close" type="func i32->i32"
Missing import: module="wasi_unstable" export="fd_write" type="func (i32, i32, i32, i32)->i32"
Missing import: module="wasi_unstable" export="path_open" type="func (i32, i32, i32, i32, i32, i64, i64, i32, i32)->i32"
```

The console.rs program produces the following error
```
Failed to link module:
Missing import: module="wasi_unstable" export="fd_write" type="func (i32, i32, i32, i32)->i32"
```

The `wasm32-unknown-wasi` (recently re-named to just `wasm32-wasi`) target is intended to be a WebAssembly target which matches the WASI proposal.

It enables features like `env::args`, `println` etc.

When I compile using Rust's `wasm32-wasi` I do get `(import "wasi_unstable" "fd_write" (func $fd_write (type 7)))` in my wat.

However when I execute in WAVM I still get the following error
```
Failed to link module:
Missing import: module="wasi_unstable" export="fd_write" type="func (i32, i32, i32, i32)->i32"
```
I have mentioned [this](https://github.com/rust-lang/rust/issues/66177) over at the rust-lang repo and am interested in finding a way to demonstrate Rust to WAVM.

[1] https://github.com/rust-lang/rust/pull/59464

Thank you so much!

**Comment by tpmccallum** [comment]
Just some additional information.
When I build using the target `wasm32-wasi` I do get an error as follows.
```
Failed to link module:
Missing import: module="wasi_unstable" export="fd_write" type="func (i32, i32, i32, i32)->i32"
```

**Comment by tpmccallum** [comment]
I see that this PR [1] is " a new wasm32-based target distributed through rustup,
supported in the standard library, and implemented in the compiler. The
wasm32-unknown-wasi target is intended to be a WebAssembly target
which matches the WASI proposal recently announced".

"it enables features like `env::args`, `println` etc.

[1] https://github.com/rust-lang/rust/pull/59464

**Comment by AndrewScheidecker** [comment]
`--abi=bare` is meant to let you execute a module without giving it access to WASI or any other host functionality.

It should work if you use `--abi=wasi`, or omit that argument and let WAVM detect that it is a WASI module.

**Comment by tpmccallum** [comment]
Thank you @AndrewScheidecker,
That worked perfectly. This is really impressive technology.
Thanks again :)

**Comment by Jessicajin-lab** [comment]
Hi,
I run the same example as @tpmccallum ran . But I meet a similar question. 
I run this
``` 
wavm run --abi=wasi --function=main ~/add_numbers_via_wavm/target/wasm32-wasi/release/adding_lib.wasm 2 2
```
Although I use `--abi=wasi`, I still get the following error:
```
Failed to link module:
Missing import: module="wasi_snapshot_preview1" export="fd_write" type="func (i32, i32, i32, i32)->i32"
```
I've learned that 'wasi_unstable' has been renamed as "wasi_snapshot_preview1" 
Thank you so much!

**Comment by AndrewScheidecker** [comment]
@Jessicajin-lab See this issue: https://github.com/WAVM/WAVM/issues/244
