### ISSUE TITLE
'main' expects 3 argument(s), but command line had 1.

### ISSUE THREAD

**Issue by tpmccallum** [WAVM/WAVM#230]
Hi @AndrewScheidecker 
I am hitting this error [1] when running the following command
`wavm run --abi=wasi --function=main ~/compression_application/target/wasm32-wasi/release/compression_application.wasm 'asdf'`
Please note that I am using `--abi=wasi`
The Rust code for the start of this main function is as follows
```
#[no_mangle]
pub extern fn main(the_input: String) {
    println!("Oringinal text: {:?}", the_input);
```
Interestingly, if I do not have a string argument like this
```
#[no_mangle]
pub extern fn main() {
    let mut input: &[u8] = b"Hello world!!! Testing, testing 1, 2, 3!!!";
```
Then the wasi run command works just fine.
```
wavm run --abi=wasi --function=main ~/compression_application/target/wasm32-wasi/release/compression_application.wasm
```
This is the output
```
Data to compress: "Hello world!!! Testing, testing 1, 2, 3!!!"

Compressed data: [27, 41, 0, 48, 140, 148, 171, 245, 228, 8, 149, 222, 49, 50, 51, 116, 50, 4, 132, 5, 54, 224, 192, 33, 13, 52, 153, 14, 133, 102, 168, 184, 250, 67, 182, 112, 24, 79, 112, 30, 231, 2]

Decompressed data As bytes [72, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 33, 33, 33, 32, 84, 101, 115, 116, 105, 110, 103, 44, 32, 116, 101, 115, 116, 105, 110, 103, 32, 49, 44, 32, 50, 44, 32, 51, 33, 33, 33]
```

[1] 
`'main' expects 3 argument(s), but command line had 1.`
At the following location https://github.com/WAVM/WAVM/blob/b055c3e20ad938e0be0e724cd970674b72bab6ab/Programs/wavm/wavm-run.cpp#L648

**Comment by AndrewScheidecker** [comment]
I think there's some problem with WAVM here, but I think Rust is also not doing what you expect with the main function that takes a string argument. If you name it something other than `main`, does it behave differently?

**Comment by tpmccallum** [comment]
Hi @AndrewScheidecker 
Thanks for looking into this for me.
If I rename the function i.e. `compress` instead of `main` like this
```
#[no_mangle]
pub extern fn compress(the_input: String) {
    println!("Oringinal text: {:?}", the_input);
}
```
and then call it like this 
```
wavm run --abi=wasi --function=compress ~/compression_application/target/wasm32-wasi/release/compress_lib.wasm "asdf"
```
I still get the same error which is 
```
compress expects 3 argument(s), but command line had 1.
```

**Comment by tpmccallum** [comment]
Also just sharing the following, from a Rust perspective.
If I split this up into two functions and then call them separately, the one that requires an argument to be passed in produces the error.
```
#[no_mangle]
pub extern "C" fn print_it(msg: &str) {
    println!("msg = {}", msg);
}

#[no_mangle]
pub extern "C" fn main() {
    let string = "hello world".to_string();
    print_it(&string);
}
```
Calling `main` no argument
```
wavm run --abi=wasi --function=main ~/compression_application/target/wasm32-wasi/release/compress_lib.wasm
```
```
msg = hello world
```
Calling `print_it` with an argument of "asdf"
```
wavm run --abi=wasi --function=print_it ~/compression_application/target/wasm32-wasi/release/compress_lib.wasm "asdf"
```
```
'print_it' expects 2 argument(s), but command line had 1.
```

**Comment by AndrewScheidecker** [comment]
WAVM doesn't support passing strings as function arguments. It does support WASI/Emscripten command line arguments, but to support it for arbitrary functions it would need to know about how the language represents strings, allocates memory for the strings, etc. This is the kind of problem that the [interface types](https://github.com/WebAssembly/interface-types) proposal is trying to solve.

**Comment by tpmccallum** [comment]
Thanks @AndrewScheidecker
I will read that proposal and also put some more thought into how I interact with WAVM.
Thanks again!
