### ISSUE TITLE
Diagnosing memory growth failures

### ISSUE THREAD

**Issue by Shillaker** [WAVM/WAVM#235]
I'm having trouble diagnosing and potentially recovering from failures of [`Runtime::growMemory`](https://github.com/WAVM/WAVM/blob/master/Lib/Runtime/Memory.cpp#L192). Currently it returns `false` on multiple error conditions, and if it fails before setting `outOldNumPages` this uninitialized value can confuse things further. I can't find a convenient way to check the failure condition without writing similar checks to the function itself.

Would it be ok to go back to having an integer return value with some predefined error codes? If you'd like to keep the boolean return value then could an `errno`-like integer be useful to interrogate if the user wishes? 

Cheers

**Comment by AndrewScheidecker** [comment]
I think it would be best for `Runtime::growMemory` to return an enum that encodes whether the operation succeeded, or the specific condition that caused it to fail.

**Comment by Shillaker** [comment]
Ah amazing, thanks Andrew!
