### ISSUE TITLE
Unify assert_result* assertions

### ISSUE THREAD

**Issue by Honry** [WAVM/WAVM#237]
People had reached the consensus in https://github.com/WebAssembly/simd/issues/137 to have an unified assert_result*, and which has alreadly been implemented in https://github.com/WebAssembly/spec/pull/1104, @AndrewScheidecker, we need this for WAVM as well. :)

**Comment by AndrewScheidecker** [comment]
I implemented the assertion in [this commit](https://github.com/WAVM/WAVM/commit/2e045f1da258d579215eabb113df36a8815734bb), but I didn't update all the tests yet, and so have left the old `assert_return_*_nan_*` commands in.

I will merge the updated tests from the spec repo. @Honry, can you update the SIMD test scripts to use the new syntax?

**Comment by Honry** [comment]
Thank you @AndrewScheidecker, I will update the tests soon.
