### ISSUE TITLE
Which llvm jit approach is used in wavm?

### ISSUE THREAD

**Issue by TerryGuo** [WAVM/WAVM#239]
Hi there,
As of LLVM 9, there are more than one JIT approaches in LLVM, the very old JIT, the MCJIT, the ORC JIT and the latest ORCv2 JIT. I am wondering which approach is being used in WAVM. Thanks in advance for any help.

**Comment by AndrewScheidecker** [comment]
WAVM has its own implementation of what MCJIT/ORCJIT do:
1. It directly invokes LLVM MC to emit object code to a memory buffer [here](https://github.com/WAVM/WAVM/blob/2e045f1da258d579215eabb113df36a8815734bb/Lib/LLVMJIT/LLVMCompile.cpp#L147).
2. To execute the object code, the symbols it references need to be bound to concrete values (memory addresses, or other constants), and the object code patched (aka loaded) with those symbol values. WAVM uses RuntimeDyld, the ELF/COFF/MachO loader used by both MCJIT and ORCJIT. [LLVMModule.cpp](https://github.com/WAVM/WAVM/blob/master/Lib/LLVMJIT/LLVMModule.cpp) is WAVM's code to do this.

**Comment by TerryGuo** [comment]
Many thanks Andrew, you perfectly addressed my question.
