### ISSUE TITLE
Is it possible to run WAVM Jitted object code outside WAVM?

### ISSUE THREAD

**Issue by TerryGuo** [WAVM/WAVM#241]
Hi there,
We have a special project which only allows us to use WAVM partially i.e. using WASM to JIT the input wasm file and save the object file, then load and run it in another process. This second process has no code from WAVM and it will load the wavm-jitted object file, parse it, fixup relocations and finally run it. Is this doable? If it is doable, then I assume the second process should setup something else in order to run the object code jitted by wavm. Thanks for any help.

**Comment by AndrewScheidecker** [comment]
It is possible, although it would be quite a bit of work. In addition to the code to load the object file, you'd need to reproduce most of the code in the Runtime module.

**Comment by TerryGuo** [comment]
Hi @AndrewScheidecker , 
What's the purpose of function metadata? Will they be saved in the object code ? I mean something like below in llvm ir file:

> define fastcc { i8*, {} } @functionDef4(i8*) #0 prefix [4 x i64] [i64 0, i64 ptrtoint (i8* @functionDefMutableDatas4 to i64), i64 sub (i64 ptrtoint (i8* @biasedInstanceId to i64), i64 1), i64 ptrtoint (i8* @typeId2 to i64)] personality i32 ()* @__gxx_personality_v0 !dbg !12 {
entry:

**Comment by AndrewScheidecker** [comment]
That holds mutable data that the runtime associates with the function. It's defined [here](https://github.com/WAVM/WAVM/blob/c1ebb05f0481a9a24ec3dadb4e8e58a6cc3a3884/Include/WAVM/RuntimeABI/RuntimeABI.h#L148) [This code](https://github.com/WAVM/WAVM/blob/c1ebb05f0481a9a24ec3dadb4e8e58a6cc3a3884/Lib/LLVMJIT/LLVMModule.cpp#L705) allocates it, and binds it to a `functionDefMutableDatas<N>` symbol. [This code](https://github.com/WAVM/WAVM/blob/c1ebb05f0481a9a24ec3dadb4e8e58a6cc3a3884/Lib/LLVMJIT/LLVMModule.cpp#L569) initializes the `FunctionMutableData`.

There's also some function metadata declared in the LLVM function prefix alongside the pointer to the `FunctionMutableData` struct, but that is located in the code pages that [this code](https://github.com/WAVM/WAVM/blob/master/Lib/LLVMJIT/LLVMModule.cpp#L207) makes read-only after loading.

The generated code doesn't access it, so you don't need to reproduce the RuntimeABI definition, but can put whatever mutable data your runtime needs to associate with the function there.

**Comment by TerryGuo** [comment]
Thank again, Andrew.
