### ISSUE TITLE
Rename wasi_unstable to wasi_snapshot_preview1

### ISSUE THREAD

**Issue by gektorbr** [WAVM/WAVM#244]
It seems most of the wasi SDKs switched from `wasi_unstable` to `wasi_snapshot_preview1`. I've tried to update wavm code renaming `wasi_unstable` to `wasi_snapshot_preview1` and it just worked. Don't have permissions to open a PR though.

**Comment by AndrewScheidecker** [comment]
> It seems most of the wasi SDKs switched from wasi_unstable to wasi_snapshot_preview1. I've tried to update wavm code renaming wasi_unstable to wasi_snapshot_preview1 and it just worked.

It would be worthwhile to resolve the same intrinsics under both the `wasi_unstable` and `wasi_snapshot_preview1` names so as to not break stuff compiled with the older SDKs.

> Don't have permissions to open a PR though.

Do you mean that GitHub won't let you create a PR on this repo? I haven't done anything that would prevent you from doing so, and other folks seem to be able to open PRs.

**Comment by AndrewScheidecker** [comment]
Fixed by da4cd279eca5a9023e3bedb80f19f5eee3bfdeb5
