### ISSUE TITLE
Example of wasm_func_call

### ISSUE THREAD

**Issue by matiasinsaurralde** [WAVM/WAVM#252]
Hi, I couldn't find a complete example of how to use `wasm_func_call`. The one in [embedder-examplace.c](https://github.com/WAVM/WAVM/blob/17801a0c4bbb491e2a4e92a0abefe5bc15a6e5cb/Examples/embedder/c/embedder-example.c) doesn't seem use any args or results parameters.

Would appreciate any guidance or docs reference.

Best.

**Comment by AndrewScheidecker** [comment]
@matiasinsaurralde I updated the embedder examples to demonstrate some basic args+results use: https://github.com/WAVM/WAVM/commit/3ca59d2ca35f2a32f282e7c4aa2b970dffc38060.

**Comment by matiasinsaurralde** [comment]
Thanks, will check it out
