### ISSUE TITLE
Magic Number Error When Disassembling Examples

### ISSUE THREAD

**Issue by pfandzelter** [WAVM/WAVM#257]
Hi, I just downloaded the [latest release (nightly/2020-02-09)](https://github.com/WAVM/WAVM/releases/tag/nightly%2F2020-02-09) for macOS and tried to disassemble the included examples (helloworld.wast and echo.wast) using `wasm disassemble`. For both, I get a `Module was malformed` error:

```
λ bin ./wavm disassemble ../share/wavm/examples/helloworld.wast helloworld.wat                                         
Module was malformed: magic number: loaded 1461730107 but was expecting 1836278016
λ bin ./wavm disassemble ../share/wavm/examples/echo.wast echo.wat                                                     
Module was malformed: magic number: loaded 1126185787 but was expecting 1836278016
```

I'm getting a similar error when using `wasm2wat`. Assembling the files myself and then disassembling them works though, so this might be a problem with the release(s).

**Comment by AndrewScheidecker** [comment]
That's the expected behavior: `wavm disassemble` only takes binary WASM files as input, and produces WAT files as output.

**Comment by pfandzelter** [comment]
Oh of course, the examples are provided as .wast, not .wasm. Got it mixed up. Thanks @AndrewScheidecker!
