### ISSUE TITLE
How to manger multi instance of one module

### ISSUE THREAD

**Issue by mrpre** [WAVM/WAVM#267]
1、I try to separate  `instance` from `module` so that I can use multi-instance to reduce the the cost of creating module.   

The following code is just a varietas of `wavm-run.cpp`:  
```
struct state {
     GCPointer<Compartment> compartment = createCompartment();
     Runtime::ModuleRef module = loadTextOrBinaryModule(xxx);

    Instance * create_instance(Module *mod)
    {
        return instantiateModule(compartment, mod, xxx)
    }

    void del_instance(Instance *instance)
    {
        //I don't know how to delete instance.  
    }
};

/*it's just an example */
int main ()
{
    state *st = new state(xxx);
    Instance *instance;
    while(;;) {
        instance = st->create_instance(mod);
        xxxxx;
        st->del_instance(instance);
    }
}
```  
I'm worrying  about the memory cost of instance so that I want free instance after I use it. How can I destroy the instance independently ？  Seems `Instance` is an inner class which I can't call `delete`. Should I add a WAVM_API like `instantiateModule` implemented by  `delete instance;`.    

I find `removeGCRoot` is used in `wavm-c.cpp` trying to decrease the counter but not delete the instance.

**Comment by mrpre** [comment]
Also, After  adding `delete instance;` by myself into code and run it, I find the instance I created is restrict by `maxMutableGlobals` :
https://github.com/WAVM/WAVM/blob/4c67bd225d53641dd93d0dc9facf57e6fcd3bf36/Lib/Runtime/Global.cpp#L26-L28  
Seems compartment can't hold too may globals and the example I write before won't work well.  

Does the WAVM have the example to show how to create multi-instance ?  

My need is pretty simple:  
1: Call wasm function with clean environment(the variable/memory should be inited) when external event comes.  I think I have to create instance for each event.  
2: Loading module takes too much time so I can't create a new module for each event.

**Comment by AndrewScheidecker** [comment]
Using `delete instance;` won't free the globals, so you'll eventually run into the per-compartment global limit as you've found.

Using `collectCompartmentGarbage` instead of just deleting the instance should solve the problem.
