### ISSUE TITLE
How to recover from WAVM runtime exceptions?

### ISSUE THREAD

**Issue by shodoco** [WAVM/WAVM#283]
Is there a way to recover from WAVM runtime exceptions (e.g. outOfBoundsMemoryAccess)? We can destroy the exception using `WAVM::Runtime:: destroyException()` but is the VM reusable (i.e. call an exported function) after destroying the exception? Is there any clean up we need to do w.r.t. the Compartment/Context?

**Comment by AndrewScheidecker** [comment]
WAVM doesn't require anything special to call back into the Context/Compartment after an exception, but it's likely that the WASM state will not be coherent after a runtime exception. For example, C programs need to be compiled with a second stack that is stored in the WASM memory, with the stack pointer in a mutable global. The stack pointer will need to be reset to avoid a stack space leak. C++ destructors will also not be called for objects that are on the stack when the runtime exception occurs.
