### ISSUE TITLE
How to compile C program with pthreads to run on WAVM

### ISSUE THREAD

**Issue by yagehu** [WAVM/WAVM#285]
On the README page of WAVM, it says:

> WAVM fully supports WebAssembly 1.0, plus many proposed extensions to it:
> 
> - WASI
> - 128-bit SIMD
> - Threads
> ...

As I understand, emscripten cannot compile standalone Wasm programs with threads, and wasi_sdk does not support threads. So how can I take advantage of the threads support on WAVM if I'm writing C or C++.

**Comment by alexthomas1** [comment]
How was this resolved? I am trying to use pthread and keep getting 

`Error loading WebAssembly binary file: Module was invalid: shared memory requires atomics feature`

**Comment by yagehu** [comment]
I never figured this out. Also, AFAIK WASI has not added specs for thread:

https://github.com/WebAssembly/wasi-sdk/issues/241
https://github.com/WebAssembly/WASI/issues/296
