### ISSUE TITLE
Add c code example about memory ?

### ISSUE THREAD

**Issue by fishioon** [WAVM/WAVM#289]
I want to pass string from host to wasm.
Is there any c code example like this?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory

**Comment by Rochet2** [comment]
1. You should start by allocating a block of memory for the string in the Wasm memory space.
    1. This could be done for example by exporting malloc from a module and by calling it from the host.
    2. Alternatively, you could allocate a page of memory from the host and work with that.
    3. The Wasm code could provide you with a pointer/index to a memory block it allocates itself.
3. Now that you have a block of memory you can write to and an index to it (returned by malloc or grow), you can use those to write to it using `memoryArrayPtr<char>(memory, memory_index, string_length)`.
    1. To the function you provide the Wasm memory object pointer, the memory index from malloc or grow and the length of the allocated block of memory.
5. The function returns a mutable char array `char*`. You copy your string there and then pass the memory_index to the Wasm function you wanted to provide the string to as a parameter.

As you may note, in this we allocate memory. A question arises about who is freeing the allocated memory.
You should decide whether the block of memory is actually provided to you by the module or allocated by the host and then who is responsible for freeing it afterward.

**Comment by AndrewScheidecker** [comment]
I've updated the C and C++ embedder examples with examples of how to marshall host strings into and out of a WebAssembly module: https://github.com/WAVM/WAVM/commit/6a1b62af3461d4da7b3aaa001f36ec240524e289.

Please feel free to reopen this issue or file a new one if you have further questions.
