### ISSUE TITLE
WAVM allocating massive space on stack when allowed max stack size is large

### ISSUE THREAD

**Issue by jaybosamiya** [WAVM/WAVM#291]
When the max stack size is unlimited (or _very_ large), WAVM starts spending a large amount of time allocating space on it, even if it doesn't need it. This can be easily seen by using `ulimit -s unlimited` and trying to run a program with WAVM (and seeing the process continue to gobble up VIRT memory via `htop`).

The commands that can be run to see this:
```bash
ulimit -s unlimited
wavm run --precompiled ./wavm-precompiled-hello-wasi.wasm
```

Below, I run it with my system's default stack size limit (8192) and with `unlimited`, while showing the results of `/usr/bin/time -v` to show the difference in execution amongst the two. To ensure that the process terminates, I also use `timeout 30s` to kill it after half a minute of execution.

In the first case (i.e., 8192) it finishes the process in _well_ under a second, but for the second, it hasn't finished even after the 30s (and by this time has allocated for itself 100s of GB of VIRT memory) before it is killed.

---

```bash
$ ulimit -s
8192
$ /usr/bin/time -v timeout 30s wavm run --precompiled ./wavm-precompiled-hello-wasi.wasm
Hello, world!
	Command being timed: "timeout 30s wavm run --precompiled ./wavm-precompiled-hello-wasi.wasm"
	User time (seconds): 0.02
	System time (seconds): 0.00
	Percent of CPU this job got: 93%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.03
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 31856
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 1
	Minor (reclaiming a frame) page faults: 5623
	Voluntary context switches: 5
	Involuntary context switches: 1
	Swaps: 0
	File system inputs: 88
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

```bash
$ ulimit -s 
unlimited
$ /usr/bin/time -v timeout 30s wavm run --precompiled ./wavm-precompiled-hello-wasi.wasm
Command exited with non-zero status 124
	Command being timed: "timeout 30s wavm run --precompiled ./wavm-precompiled-hello-wasi.wasm"
	User time (seconds): 7.75
	System time (seconds): 22.71
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:30.46
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 16872
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 86060916
	Voluntary context switches: 4
	Involuntary context switches: 27
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 124
```

**Comment by AndrewScheidecker** [comment]
WAVM has some excessively clever code to allocate the sigaltstack on top of the main stack, which helps ASAN handle the `siglongjmp` out of the signal handler correctly.

I changed it to only do that when ASAN is enabled in https://github.com/WAVM/WAVM/commit/81225ecd9a8940d064da0010d4d0f25c7f0b61d8. That should solve your problem!
