### ISSUE TITLE
/WAVM/Test/emscripten example not work

### ISSUE THREAD

**Issue by wolfplain** [WAVM/WAVM#292]
cd ~/workspace/WAVM/Test/emscripten
 ./compile.sh args.cpp 
wavm run --abi="emscripten" args.wasm
got result:
Emscripten module does not export malloc.

when i tried to use compile.sh to recomplie the file, args.wasm not work when doing wavm run; 
also i had tried to use below command it also not work. 

emcc args.cpp -o3 -std=c++11 -s  EXPORTED_FUNCTIONS="['_main','_malloc']" -s EMIT_EMSCRIPTEN_METADATA=1 -s STANDALONE_WASM=1 -o args.wasm
wavm run --abi="emscripten" args.wasm
got result:
Runtime exception: wavm.reachedUnreachable
Call stack:
  host!wavm+13901974
  wasm!importStub!importStub: environ_sizes_get ((i32, i32)->i32)+0
  wasm!args.wasm!<function #309>+21
  wasm!args.wasm!<function #1>+0
  wasm!args.wasm!<function #45>+4
  thnk!C to WASM thunk!()->()+0
  host!wavm+12635350
  host!wavm+13725301
  host!wavm+13828942
  host!wavm+11666606
  host!wavm+11656236
  host!wavm+11647509
  <2 redundant frames omitted>
  host!wavm+11645907
  host!wavm+11555109
  host!/lib/x86_64-linux-gnu/libc.so.6!__libc_start_main+239
  host!wavm+11489320

**Comment by AndrewScheidecker** [comment]
This should be fixed by https://github.com/WAVM/WAVM/commit/70a2a97f16dd3abf4f266f3580dc06791a11c548.
