### ISSUE TITLE
Out Of Bounds Memory Access

### ISSUE THREAD

**Issue by ZW007** [WAVM/WAVM#295]
Here is how i compile the C file: 
wasm32-wasi-clang   -I ./ LeNet.c main.c -lm -o mainWasi.wasm
when i run 
wavm run --mount-root ./ mainWasi.wasm 
I get the error on memory, because I need to read the model file and  t10k-images-idx3-ubyte, t10k-labels-idx1-ubyte.  around 10 MB in total. 

Runtime exception: wavm.outOfBoundsMemoryAccess(+4295038108)
Call stack:
  wasm!mainWasi.wasm!Predict+16
  wasm!mainWasi.wasm!testing+104
  wasm!mainWasi.wasm!foo+138
  wasm!mainWasi.wasm!__original_main+15
  wasm!mainWasi.wasm!_start+1
  thnk!C to WASM thunk!()->()+0
  host!/usr/lib/libWAVM.so.0!WAVM::Platform::catchSignals(void (*)(void*), bool (*)(void*, WAVM::Platform::Signal, WAVM::Platform::CallStack&&), void*)+208
  host!/usr/lib/libWAVM.so.0!WAVM::Runtime::unwindSignalsAsExceptions(std::function<void ()> const&)+73
  host!/usr/lib/libWAVM.so.0!WAVM::Runtime::invokeFunction(WAVM::Runtime::Context*, WAVM::Runtime::Function const*, WAVM::IR::FunctionType, WAVM::IR::UntaggedValue const*, WAVM::IR::UntaggedValue*)+455
  host!wavm+219871
  host!/usr/lib/libWAVM.so.0!WAVM::WASI::catchExit(std::function<int ()>&&)+15
  host!wavm+212849
  host!wavm+203749
  <2 redundant frames omitted>
  host!/usr/lib/libWAVM.so.0!WAVM::Runtime::catchRuntimeExceptions(std::function<void ()> const&, std::function<void (WAVM::Runtime::Exception*)> const&)+18
  host!wavm+202625
  host!wavm+125621
  host!/lib/x86_64-linux-gnu/libc.so.6!__libc_start_main+230
  host!wavm+61480

Aborted (core dumped)

I wonder if i allocate more memory for wavm?

**Comment by AndrewScheidecker** [comment]
WASI should dynamically grow the WASM memory as needed for memory allocations.

The `wavm.outOfBoundsMemoryAccess` runtime exception indicates that your WASM program accessed an invalid address, and is analogous to a SIGSEGV if you were running it as a native program. This is almost certainly a bug in your program.
