### ISSUE TITLE
First execution time of a wasm function is slow

### ISSUE THREAD

**Issue by bruzer129** [WAVM/WAVM#300]
Hi,

When I load a wasm binary and execute any function within that binary for the first time, the execution is slow.  Subsequent executions are fast.

For example: multiply 2 numbers
- 1st: 0.004524166 sec  (4.5 msec)
- 2nd: 0.000029169 sec (29 usec)

Square:
- 1st: 0.002558924 sec
- 2nd: 0.000028646 sec

When the wasm is loaded, I get this metrics logging:
20210118-193855.551 :DEBUG: Loaded WASM in 0.32ms (0.678234 MiB/s)
20210118-193855.553 :DEBUG: Emitted LLVM IR in 0.44ms (16062.266523 functions/s)
20210118-193855.554 :DEBUG: Optimized LLVM module in 1.06ms (6614.762828 functions/s)
20210118-193855.563 :DEBUG: Generated machine code in 8.78ms (911.003188 functions/s)
20210118-193855.564 :DEBUG: Loaded /home/bruzer/CCE/four_funcs.wasm in 0.24ms (12.553123 MiB/s)
20210118-193855.564 :DEBUG: Code: 0.3 KiB, read-only data: 1.9 KiB, read-write data: 0.0 KiB

Is there something I can do after loading a wasm binary so that each function execution is fast as it can be?

Note, I cannot execute each function 1 time before turning it over to a client to make requests, because the wasm they
supplied might maintain state information for each function call.

Thank you,
-Bruce Evans

**Comment by AndrewScheidecker** [comment]
The first time you call a function with a particular signature, it must compile a thunk for that signature. You should be able to front load most of the cost by calling `LLVMJIT::getInvokeThunk(functionType)` for each function signature (as a `FunctionType`) you expect to call.

**Comment by bruzer129** [comment]
Thank you Andrew. I will give that a try.  Also, thank you very much for all the work you have done with this library. I'm slowing getting used to it. I'm sure there is a general way to parse a wasm binary and how to prepare it for use and I was looking for more of the particulars in how WAVM does that, but it seems to be more in the code than textual.

**Comment by bruzer129** [comment]
Andrew, I implemented your suggestion and am not seeing an improvement. When I read in the wasm binary, I create the Thunks. I have a bunch of debug checking, and the Thunks do not exist at this time, so I create them then re-verify they are there. Later on when a request comes in, I verify a Thunk exists for a Runtime::Function.  I get this function using asFunctionNullable(getInstanceExport(instance, func_name)).  I then call Runtime::invokeFunction(context, function, func_type, parms, result)

At the end of Runtime::invokeFunction() is the call (*invokeContext.invokeThunk)( params ...)  What is happening here?  Is this the machine code being executed or could there be some other checking going on? 

I may add some debug code to the WAVM invokeFunction() to see if it thinks there is no Thunk.  That is the only place I would think that could be adding time. I actually copied this code and put in my app, so this should not be the case. I'll follow up once I find out. Thanks.

**Comment by bruzer129** [comment]
Update: Here are some results I am seeing by creating a Thunk for each exported function in the wasm binary when that binary is read in, and at a later time, requests to execute any function from that binary.

If functions have the same Signature, like (uint, uint), then the first Thunk compile is ~3-9ms.  Any function with the same signature that has a Thunk compiled after the 1st is < 1us.  So up front, the major cost is for the first func with a specific Signature. This time is a don't care for me since I am only loading the binary and preparing it.

When a request comes in to execute a function from the binary, my tests showed that ONLY the first function request took ~3-9ms and then any other function, independent of the Signature would take < 100us.  I'm curious why only the first function took so long, even though the Thunk existed.

# Reading wasm binary and creating a Thunk for each exported function
# Note how the first Thunk compile for a function(signature) is in msec, while the next
# Thunk compile for any function with the same signature is < 1usec.
# e.g. add/add2

20210125-143448.532 :INFO: 10 Function(s) in Module
20210125-143448.537 :INFO: Created Thunk for: square
20210125-143448.538 :INFO: getInvokeThunk ExecTime: 0.005258971 sec
20210125-143448.538 :INFO: Index/Function: 0/square: Param[1]: i32, Result[1]: i32,
20210125-143448.538 :INFO: Created Thunk for: square2
20210125-143448.538 :INFO: getInvokeThunk ExecTime: 0.000008964 sec
20210125-143448.538 :INFO: Index/Function: 1/square2: Param[1]: i32, Result[1]: i32,
20210125-143448.545 :INFO: Created Thunk for: sub
20210125-143448.545 :INFO: getInvokeThunk ExecTime: 0.006073612 sec
20210125-143448.545 :INFO: Index/Function: 2/sub: Param[1]: i32, Param[2]: i32, Result[1]: i32,
20210125-143448.548 :INFO: Created Thunk for: div
20210125-143448.548 :INFO: getInvokeThunk ExecTime: 0.003074186 sec
20210125-143448.548 :INFO: Index/Function: 3/div: Param[1]: i32, Param[2]: i32, Param[3]: i32, Result[1]: i32,
20210125-143448.551 :INFO: Created Thunk for: **add**
20210125-143448.551 :INFO: getInvokeThunk ExecTime: 0.002776089 sec
20210125-143448.551 :INFO: Index/Function: 4/add: Param[1]: i32, Param[2]: i32, Param[3]: i32, Param[4]: i32, Result[1]: i32,
20210125-143448.559 :INFO: Created Thunk for: mul
20210125-143448.560 :INFO: getInvokeThunk ExecTime: 0.008628885 sec
20210125-143448.560 :INFO: Index/Function: 5/mul: Param[1]: i32, Param[2]: i32, Param[3]: i32, Param[4]: i32, Param[5]: i32, Result[1]: i32,
20210125-143448.560 :INFO: Created Thunk for: sub2
20210125-143448.560 :INFO: getInvokeThunk ExecTime: 0.000001132 sec
20210125-143448.560 :INFO: Index/Function: 6/sub2: Param[1]: i32, Param[2]: i32, Result[1]: i32,
20210125-143448.560 :INFO: Created Thunk for: div2
20210125-143448.560 :INFO: getInvokeThunk ExecTime: 0.000000319 sec
20210125-143448.560 :INFO: Index/Function: 7/div2: Param[1]: i32, Param[2]: i32, Param[3]: i32, Result[1]: i32,
20210125-143448.560 :INFO: Created Thunk for: **add2**
20210125-143448.560 :INFO: getInvokeThunk ExecTime: 0.000000217 sec
20210125-143448.560 :INFO: Index/Function: 8/add2: Param[1]: i32, Param[2]: i32, Param[3]: i32, Param[4]: i32, Result[1]: i32,
20210125-143448.560 :INFO: Created Thunk for: mul2
20210125-143448.560 :INFO: getInvokeThunk ExecTime: 0.000000223 sec
20210125-143448.560 :INFO: Index/Function: 9/mul2: Param[1]: i32, Param[2]: i32, Param[3]: i32, Param[4]: i32, Param[5]: i32, Result[1]: i32,

# Execute requests for a wasm function
# Note how only the first function exe time is in msec (mul), while the subsequent functions
# sub and square are in usec.

20210125-143600.705 :INFO: Execute: Function Name/Idx/Args: mul/5/2,3,4,5,6,
20210125-143600.705 :INFO: Found Thunk for: mul
20210125-143600.708 :INFO: wasmres[0]: 720
20210125-143600.708 :INFO: WASM ExecTime: 0.002716862 sec

20210125-143625.889 :INFO: Execute: Function Name/Idx/Args: sub/2/20,13,
20210125-143625.889 :INFO: Found Thunk for: **sub**
20210125-143625.889 :INFO: wasmres[0]: 7
20210125-143625.889 :INFO: WASM ExecTime: 0.000038640 sec

20210125-143650.222 :INFO: Execute: Function Name/Idx/Args: square/0/23,
20210125-143650.222 :INFO: Found Thunk for: **square**
20210125-143650.222 :INFO: wasmres[0]: 529
20210125-143650.222 :INFO: WASM ExecTime: 0.000043861 sec

**Comment by bruzer129** [comment]
I modified libWAVM to print if it did not find a Thunk  in Runtime::invokeFunction()
My code calls LLVMJIT::getInvokeThunk() to create the Thunk for each wasm function when I read in the wasm binary.
invokeFunction() always found a Thunk in the below debug for client requests.

I also modified invokeFunction() to time the call for invoking the Thunk:  (*invokeContext.invokeThunk)( ... parms ...);
The interesting debug is that the first function to be invoked, took ~6ms to execute (it already had a Thunk) and all
subsequent functions invoked took < 10usec.

@AndrewScheidecker why would only the first invoked function take 100x as long as any subsequent function, when all of the functions had a Thunk created at wasm load time? Please see the debug log below.  Thanks.

20210126-162500.274 :INFO: 11 Function(s) in Module
20210126-162500.278 :DEBUG: Create Thunk (init): 3.531308000 msec
20210126-162500.281 :DEBUG: Create Thunk (square): 3.393987000 msec
20210126-162500.281 :DEBUG: Create Thunk (square2): 860.000000000 nsec
20210126-162500.285 :DEBUG: Create Thunk (sub): 3.388323000 msec
20210126-162500.285 :DEBUG: Create Thunk (sub2): 1.037000000 usec
20210126-162500.288 :DEBUG: Create Thunk (div): 3.040210000 msec
20210126-162500.288 :DEBUG: Create Thunk (div2): 1.367000000 usec
20210126-162500.294 :DEBUG: Create Thunk (add): 5.760423000 msec
20210126-162500.294 :DEBUG: Create Thunk (add2): 14.910000000 usec
20210126-162500.302 :DEBUG: Create Thunk (mul): 7.560951000 msec
20210126-162500.302 :DEBUG: Create Thunk (mul2): 781.000000000 nsec

// Here is where I invoke the init() function. This is not a client request. I do it after loading
// the wasm binary and creating Thunks for all the functions in it, as shown above.
// Here we see that even though a Thunk exists for init(), it takes 6.25ms to execute

20210126-162500.302 :INFO: init_found: func_params size: 0, wasm_res size: 0
20210126-162500.302 :DEBUG: invokeFunction(): Thunk exists  <--- getInvokeFunction() will not be called in this case
20210126-162500.309 :DEBUG: *invokeContext.invokeThunk: 0.006255722 sec

// A client request to execute function square()
// The square() function executes in 4.9usec, almost 100x faster than init()

20210126-162913.577 :DEBUG: POLL Event on fd: 5
20210126-162913.577 :DEBUG: invokeFunction(): Thunk exists  <----
20210126-162913.577 :DEBUG: *invokeContext.invokeThunk: 0.000004911 sec
20210126-162913.577 :INFO: Executed: Function Name/Idx/Args: square/1/7,

// A client request to execute the init() function again
// The init() function executes in 3usec

20210126-162948.285 :DEBUG: POLL Event on fd: 5
20210126-162948.285 :DEBUG: invokeFunction(): Thunk exists <----
20210126-162948.285 :DEBUG: *invokeContext.invokeThunk: 0.000003059 sec
20210126-162948.286 :INFO: Executed: Function Name/Idx/Args: init/0/

**Comment by AndrewScheidecker** [comment]
I think what's you're seeing is that the signal handler is set up the first time `Platform::catchSignals` is called, which normally only happens when you invoke a function.

You can try doing something like this before invoking a function and see if it makes the subsequent invocation faster:
```
Platform::catchSignals([](void*){}, [](void*, Platform::Signal, Platform::CallStack&&){}, nullptr);
```

**Comment by bruzer129** [comment]
Darn, I thought I posted this a couple weeks ago.

@AndrewScheidecker The above hint is giving me a compile error. I've tried several things to no avail.

        bool boolvar = WAVM::Platform::catchSignals([](void*){},                                         
          [](void*, WAVM::Platform::Signal, WAVM::Platform::CallStack&&){},                              
          nullptr);    

#> make
Scanning dependencies of target cce
[ 50%] Building CXX object CMakeFiles/cce.dir/cce.cpp.o
clang: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]
/home/bruzer/Repos/cce/cce/cce.cpp:907:11: error: no viable conversion from '(lambda at /home/bruzer/Repos/cce/cce/cce.cpp:907:11)' to 'bool (*)(void *, WAVM::Platform::Signal, WAVM::Platform::CallStack &&)'
          [](void*, WAVM::Platform::Signal, WAVM::Platform::CallStack&&){},
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/bruzer/Repos/cce/cce/cce.cpp:907:11: note: candidate function
/usr/local/include/WAVM/Platform/Signal.h:30:18: note: passing argument to parameter 'filter' here
                                                           bool (*filter)(void*, Signal, CallStack&&),
                                                                  ^
1 error generated.
make[2]: *** [CMakeFiles/cce.dir/build.make:63: CMakeFiles/cce.dir/cce.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/cce.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by bruzer129** [comment]
I was hoping Andrew would comment on the above. Maybe he still will.  Closing this issue. Thanks for all previous responses.
