### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by vshymanskyy** [WAVM/WAVM#314]
System: `Ubuntu 21.04 x64`
WAVM: https://github.com/WAVM/WAVM/releases/tag/nightly%2F2021-04-03

**Steps:**
```sh
git clone https://github.com/wasm3/wasm3-self-compiling.git

cd wasm3-self-compiling

wavm run --mount-root . ./wasm/clang.wasm  -cc1 -triple wasm32-unknown-wasi -isysroot /sys -internal-isystem /sys/include -emit-obj -o source/hello/hello.o source/hello/hello.c -O3

wavm run --mount-root . ./wasm/wasm-ld.wasm  -L/sys/lib/wasm32-wasi /sys/lib/wasm32-wasi/crt1.o -lc -o hello.wasm source/hello/hello.o -O3 -s
```

First command takes ~5 minutes, second ~3 minutes, every time the command is executed.
After commands start executing, they fail due to [this issue](https://github.com/WAVM/WAVM/issues/155#issuecomment-833809155), but it's unrelated.

**Expected result:** first time the module takes long time to compile, consequent runs should be much faster.

**Comment by AndrewScheidecker** [comment]
Do you have the `WAVM_OBJECT_CACHE_DIR` environment variable set? See https://github.com/WAVM/WAVM/blob/master/Doc/GettingStarted.md#set-up-an-object-cache

It doesn't use a cache unless you manually set that environment variable to point to some directory.

**Comment by vshymanskyy** [comment]
My bad, `WAVM_OBJECT_CACHE_DIR` was not exported :grinning:
