### ISSUE TITLE
WASI `args_get` issue

### ISSUE THREAD

**Issue by vshymanskyy** [WAVM/WAVM#315]
Initially reported in https://github.com/WAVM/WAVM/issues/155#issuecomment-833809155, here's more info on this issue.

To reproduce the issue, download `uutils.wasm` from wapm: https://wapm.io/package/coreutils#explore
```sh
$ wavm run --mount-root . uutils.wasm ls -l ./
exe: applet not found
```
Other engines:
```sh
$ wasm3 uutils.wasm ls -l ./
---------- 1 somebody somegroup  2221485 2021-05-07 05:59 uutils.wasm

$ wasmer run --mapdir=.:. uutils.wasm -- ls -l ./
---------- 1 somebody somegroup  2221485 2021-05-07 05:59 uutils.wasm

$ wasm-run uutils.wasm -- ls -l /
---------- 1 somebody somegroup  2221485 2021-05-07 05:59 uutils.wasm
```

It appears to be a problem with the args[0] parameter. WAVM passes `/proc/1/exe` while other runtimes pass the wasm file path like `uutils.wasm` (exactly as it was passed to them)

**Comment by AndrewScheidecker** [comment]
This is easy to fix, but it seems undesirable to implicitly expose any information about the host filesystem. Do other runtimes pass exactly what was given to them as an argument, or do they strip it down to just the filename?

**Comment by vshymanskyy** [comment]
Thanks!
