### ISSUE TITLE
Can't compile on Win10

### ISSUE THREAD

**Issue by rygo6** [WAVM/WAVM#325]
I am trying to compile and get this error over and over:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0135	class "llvm::AttributeList" has no member "addAttribute"	libWAVM	C:\Developer\WAVM\Lib\LLVMJIT\LLVMJITPrivate.h	329	
```

This is the cmake command I used to generate my project:
```
cmake ../WAVM -G "Visual Studio 16 2019" -DLLVM_DIR=/c/Developer/llvm-project/build/lib/cmake/llvm/
```

Does WAVM only build against a certain version of LLVM? Has anyone run into this?

**Comment by AndrewScheidecker** [comment]
It doesn't compile against *all* versions of LLVM, but it should compile against LLVM 9-12. Haven't tried 13 yet.

**Comment by rygo6** [comment]
Compiling with llvm 12 that I built from source worked, thank you.
