### ISSUE TITLE
Cannot build from source?

### ISSUE THREAD

**Issue by ERICXUCHI** [WAVM/WAVM#326]
As I run `cmake`, some error happens, it seems like target miss? 
Here is my command and version of tools. `Ubuntu20.04`
Thanks!
![image](https://user-images.githubusercontent.com/57583292/143901515-dff3d15f-30e4-4edf-b52e-7b85224e5c28.png)

**Comment by therahulkanyal** [comment]
Install `zlib`  and `zlib-dev`.
`$ sudo apt install zlib zlib-dev`

**Comment by ERICXUCHI** [comment]
Thanks! It works, thank you very much!
