### ISSUE TITLE
Launching code compiled with emcc

### ISSUE THREAD

**Issue by sletz** [WAVM/WAVM#59]
I am trying to load code compiled with **emcc** (version 1.37.21). So compiling the simple code:
 
```
#include <iostream>

int main(int argc,char** argv)
{
    std::cout << "Hello world!\n";
}
```
with : emcc hello.cpp -s WASM=1 -o hello.js which creates the **hello.js**  and associated **hello.wasm** files.

The  using: **wavm hello.wasm** fails with missing symbols, like:

```
Generated stub for missing function import env.enlargeMemory : func ()->i32
Generated stub for missing function import env.getTotalMemory : func ()->i32
Generated stub for missing function import env.abortOnCannotGrowMemory : func ()->i32
...
Runtime exception: reached unreachable code

```
So I guess the Emscripten runtime is somewhat missing.  How can we load code compiled with emcc ?

**Comment by AndrewScheidecker** [comment]
I can reproduce this, but if I implement these functions as in the Emscripten js code, I get an access violation exception, so I need to dig into the Emscripten changes a little bit more before I can fix this.

**Comment by AndrewScheidecker** [comment]
Please try [this commit](https://github.com/AndrewScheidecker/WAVM/commit/3995451c11bad95b6c34edb0417a0b4d6780f771). I implemented enough that it can run the benchmark/zlib tests as compiled by the latest Emscripten.
