### ISSUE TITLE
Support AArch64 hosts

### ISSUE THREAD

**Issue by AndrewScheidecker** [WAVM/WAVM#76]
There are a few components to this:

* There's some CPU-specific C and assembly code in Platform, used for forking threads. That needs to be ported to AArch64.

* It's necessary to use platform-specific LLVM intrinsics for many SIMD operations (e.g. saturating addition and min/max). WAVM currently only generates SSE intrinsics, but it should instead look at the target architecture and generate the appropriate intrinsics when targeting AArch64.

**Comment by gnanasekar-somanathan** [comment]
I tried building for android toolchain. and got following error while compiling.
Can you guide me what needs to be ported to AArch64. 

Building Android release (aarch64)...
[1/23] Building ASM object CMakeFiles/WAVM.dir/Lib/Platform/POSIX/POSIX.S.o
FAILED: CMakeFiles/WAVM.dir/Lib/Platform/POSIX/POSIX.S.o 
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as -DEMSCRIPTEN_API="" -DIR_API="" -DLLVMJIT_API="" -DLOGGING_API="" -DNFA_API="" -DPLATFORM_API="" -DREGEXP_API="" -DRUNTIME_API="" -DTHREADTEST_API="" -DWASM_API="" -DWASTPARSE_API="" -DWASTPRINT_API="" -DWAVM_C_API="" -DWAVM_EXPORTS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I../../Include -IInclude -I../../ThirdParty/libunwind/include -I/usr/lib/llvm-6.0/include -O3 -DNDEBUG -fPIC   -Wall -Werror -fPIC -fno-omit-frame-pointer -MD -MT CMakeFiles/WAVM.dir/Lib/Platform/POSIX/POSIX.S.o -MF CMakeFiles/WAVM.dir/Lib/Platform/POSIX/POSIX.S.o.d -o CMakeFiles/WAVM.dir/Lib/Platform/POSIX/POSIX.S.o -c ../../Lib/Platform/POSIX/POSIX.S
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as: invalid option -- 'E'
[2/23] Building ASM object ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o
FAILED: ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o 
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as  -I../../ThirdParty/libunwind/include -O3 -DNDEBUG   -fPIC -MD -MT ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o -MF ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o.d -o ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersRestore.S.o -c ../../ThirdParty/libunwind/src/UnwindRegistersRestore.S
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as: unrecognized option '-O3'
[3/23] Building ASM object ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o
FAILED: ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o 
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as  -I../../ThirdParty/libunwind/include -O3 -DNDEBUG   -fPIC -MD -MT ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o -MF ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o.d -o ThirdParty/libunwind/CMakeFiles/WAVMUnwind.dir/src/UnwindRegistersSave.S.o -c ../../ThirdParty/libunwind/src/UnwindRegistersSave.S
/home/gnanasekar/Android/Sdk//ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android-as: unrecognized option '-O3'

**Comment by rmnoff** [comment]
hello, @AndrewScheidecker! I found WAVM browsing my issue regarding js running in iOS. It looks like WAVM might help me solve many of problems I potentially may face in the future. I would love to know if there are news regarding iOS & Android ports? Thank you!

**Comment by AndrewScheidecker** [comment]
There hasn't been any progress on iOS or Android ports of WAVM.

**Comment by AndrewScheidecker** [comment]
As of https://github.com/WAVM/WAVM/commit/85d898acde8126e271041d36897c4915dabb20fa, WAVM mostly works on AArch64 Ubuntu 18.04. There are a few remaining issues:
* AArch64 only works with WAVM_ENABLE_UNWIND=0.
* LLVM doesn't yet (as of version 9.0) implement stack probes for AArch64, so the skip-stack-guard-page test fails.
* Misaligned stores that are partially out-of-bounds may partially write to the in-bounds memory before trapping. This causes these two tests to fail:
  * https://github.com/WAVM/WAVM/blob/3e7fb76a301fe839d58bb66ddfafe697a47b4223/Test/spec/memory_trap.wast#L269
  * https://github.com/WAVM/WAVM/blob/3e7fb76a301fe839d58bb66ddfafe697a47b4223/Test/spec/align.wast#L866
* The `sqrt` tests in wabt_simd_unary.wast fail due to producing a different NaN than X86 (positive instead of negative). In this case, the tests are more restrictive than the spec. Unfortunately, there isn't a SIMD equivalent of `assert_<canonical|arithmetic>_nan` to make the test more tolerant of different NaNs.

**Comment by AndrewScheidecker** [comment]
As of https://github.com/WAVM/WAVM/commit/511d079d445402f4a2f1779f248846209f455c26, WAVM is tested on AArch64 by Travis CI.

The stack probes are the only remaining issue, which I've opened #205 to track.

**Comment by didi11641** [comment]
> As of [85d898a](https://github.com/WAVM/WAVM/commit/85d898acde8126e271041d36897c4915dabb20fa), WAVM mostly works on AArch64 Ubuntu 18.04.

Hi, I'm wondering whether WAVM can run on Android? If it does, could you please give some compiling instructions?
