### ISSUE TITLE
Execute on iOS/Android

### ISSUE THREAD

**Issue by aloisdeniel** [WAVM/WAVM#84]
Hi,

First congratulation for the work!

Before investing too much time into it, would it be possible to run the VM from an iOS or Android application? This would allow to run wasm programs and interrop with it!

Thanks!

**Comment by AndrewScheidecker** [comment]
It won't work right now, as there's a small amount of assembly code needs to be ported to ARM. With that assembly code ported to ARM, it should work, but further changes to WAVM are probably necessary to make it practical.

In particular, WAVM doesn't have any capability to compile WASM->native code ahead of time and distribute it. It can only compile the WASM byte code to native code when you want to run it (i.e. JIT). I understand that the iOS app store prohibited JIT compilation in the past, but that it might be allowed in limited circumstances now. Still, Apple would probably prefer that you don't do it.

Additionally, WAVM uses LLVM to generate native code, which is relatively slow for a JIT, but produces high quality code. On a mobile-class CPU, it's probably painfully slow for any non-trivial WebAssembly module.

I would like to add the capability to cache the compiled native code on disk, so it doesn't need to be recompiled every time you run WAVM. However, I'm not actively working on that right now, so you shouldn't count on it getting done.

**Comment by aloisdeniel** [comment]
Okay, thanks for clarifying all of that!

I'm thinking of a unified way to run an application(*compiled to wasm*) from various platforms and interpreting a tree structure out of it for rendering it. So basically, you would have to subscribe to a callback with the tree updates (*from wasm*), and a channel for sending (*to wasm*) simple actions (user input, layout size changes...).

Another question, how does this project compare to [wasmint](https://github.com/WebAssembly/wasmint)?

**Comment by AndrewScheidecker** [comment]
I created an issue to port WAVM to AArch64 hosts: https://github.com/WAVM/WAVM/issues/76. AFAIK that's the only issue blocking running on iOS and Android.
