### ISSUE TITLE
compile with afl-fast-clang failed

### ISSUE THREAD

**Issue by maldiohead** [WAVM/WAVM#89]
![default](https://user-images.githubusercontent.com/23315692/41906449-70e86220-7970-11e8-8f9f-0645ecdebcf7.png)

how to solve the problem?

**Comment by AndrewScheidecker** [comment]
IIRC, I ran into that problem once using a binary distribution of LLVM that was compiled with a different version of GCC than I was using to compile WAVM. More info here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by maldiohead** [comment]
so  how to solve the problem?

**Comment by AndrewScheidecker** [comment]
The bulletproof way to solve the problem would be to build LLVM from source with afl-clang-fast.

**Comment by AndrewScheidecker** [comment]
Please feel free to re-open if you're still having trouble.
